// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_bd.toml -o tests/test_bd.t.a.c
//

#include "runners/test_runner.h"

#ifndef PROG
#define PROG_i                   TEST_IMPLICIT_DEFINE_COUNT+0
#define PROG                     TEST_DEFINE(PROG_i)
#endif
#ifndef READ
#define READ_i                   TEST_IMPLICIT_DEFINE_COUNT+1
#define READ                     TEST_DEFINE(READ_i)
#endif

intmax_t __test__test_bd_one_block__PROG__0(__attribute__((unused)) void *data) {
    return PROG_SIZE;
}

intmax_t __test__test_bd_one_block__READ__0(__attribute__((unused)) void *data) {
    return READ_SIZE;
}

intmax_t __test__test_bd_one_block__READ__1(__attribute__((unused)) void *data) {
    return BLOCK_SIZE;
}

const test_define_t __test__test_bd_one_block__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [PROG_i                  ] = {__test__test_bd_one_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_one_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_one_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_one_block__READ__1, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_one_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_one_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_one_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_one_block__READ__1, NULL},
    },
};

void __test__test_bd_one_block__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_bd_one_block
    #line 11 "tests/test_bd.toml"
    uint8_t buffer[lfs_max(READ, PROG)];

    // write data
    cfg->erase(cfg, 0) => 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
        for (lfs_off_t j = 0; j < PROG; j++) {
            buffer[j] = (i+j) % 251;
        }
        cfg->prog(cfg, 0, i, buffer, PROG) => 0;
    }

    // read data
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, 0, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (i+j) % 251);
        }
    }
    #line 71 "tests/test_bd.t.a.c"
}

intmax_t __test__test_bd_two_block__PROG__0(__attribute__((unused)) void *data) {
    return PROG_SIZE;
}

intmax_t __test__test_bd_two_block__READ__0(__attribute__((unused)) void *data) {
    return READ_SIZE;
}

intmax_t __test__test_bd_two_block__READ__1(__attribute__((unused)) void *data) {
    return BLOCK_SIZE;
}

const test_define_t __test__test_bd_two_block__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [PROG_i                  ] = {__test__test_bd_two_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_two_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_two_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_two_block__READ__1, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_two_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_two_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_two_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_two_block__READ__1, NULL},
    },
};

void __test__test_bd_two_block__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_bd_two_block
    #line 36 "tests/test_bd.toml"
    uint8_t buffer[lfs_max(READ, PROG)];
    lfs_block_t block;

    // write block 0
    block = 0;
    cfg->erase(cfg, block) => 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
        for (lfs_off_t j = 0; j < PROG; j++) {
            buffer[j] = (block+i+j) % 251;
        }
        cfg->prog(cfg, block, i, buffer, PROG) => 0;
    }

    // read block 0
    block = 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }

    // write block 1
    block = 1;
    cfg->erase(cfg, block) => 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
        for (lfs_off_t j = 0; j < PROG; j++) {
            buffer[j] = (block+i+j) % 251;
        }
        cfg->prog(cfg, block, i, buffer, PROG) => 0;
    }

    // read block 1
    block = 1;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }

    // read block 0 again
    block = 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }
    #line 160 "tests/test_bd.t.a.c"
}

intmax_t __test__test_bd_last_block__PROG__0(__attribute__((unused)) void *data) {
    return PROG_SIZE;
}

intmax_t __test__test_bd_last_block__READ__0(__attribute__((unused)) void *data) {
    return READ_SIZE;
}

intmax_t __test__test_bd_last_block__READ__1(__attribute__((unused)) void *data) {
    return BLOCK_SIZE;
}

const test_define_t __test__test_bd_last_block__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [PROG_i                  ] = {__test__test_bd_last_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_last_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_last_block__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_last_block__READ__1, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_last_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_last_block__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_last_block__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_last_block__READ__1, NULL},
    },
};

void __test__test_bd_last_block__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_bd_last_block
    #line 94 "tests/test_bd.toml"
    uint8_t buffer[lfs_max(READ, PROG)];
    lfs_block_t block;

    // write block 0
    block = 0;
    cfg->erase(cfg, block) => 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
        for (lfs_off_t j = 0; j < PROG; j++) {
            buffer[j] = (block+i+j) % 251;
        }
        cfg->prog(cfg, block, i, buffer, PROG) => 0;
    }

    // read block 0
    block = 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }

    // write block n-1
    block = cfg->block_count-1;
    cfg->erase(cfg, block) => 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
        for (lfs_off_t j = 0; j < PROG; j++) {
            buffer[j] = (block+i+j) % 251;
        }
        cfg->prog(cfg, block, i, buffer, PROG) => 0;
    }

    // read block n-1
    block = cfg->block_count-1;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }

    // read block 0 again
    block = 0;
    for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
        cfg->read(cfg, block, i, buffer, READ) => 0;

        for (lfs_off_t j = 0; j < READ; j++) {
            LFS_ASSERT(buffer[j] == (block+i+j) % 251);
        }
    }
    #line 249 "tests/test_bd.t.a.c"
}

intmax_t __test__test_bd_powers_of_two__PROG__0(__attribute__((unused)) void *data) {
    return PROG_SIZE;
}

intmax_t __test__test_bd_powers_of_two__READ__0(__attribute__((unused)) void *data) {
    return READ_SIZE;
}

intmax_t __test__test_bd_powers_of_two__READ__1(__attribute__((unused)) void *data) {
    return BLOCK_SIZE;
}

const test_define_t __test__test_bd_powers_of_two__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [PROG_i                  ] = {__test__test_bd_powers_of_two__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_powers_of_two__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_powers_of_two__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_powers_of_two__READ__1, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_powers_of_two__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_powers_of_two__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_powers_of_two__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_powers_of_two__READ__1, NULL},
    },
};

void __test__test_bd_powers_of_two__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_bd_powers_of_two
    #line 152 "tests/test_bd.toml"
    uint8_t buffer[lfs_max(READ, PROG)];

    // write/read every power of 2
    lfs_block_t block = 1;
    while (block < cfg->block_count) {
        // write
        cfg->erase(cfg, block) => 0;
        for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
            for (lfs_off_t j = 0; j < PROG; j++) {
                buffer[j] = (block+i+j) % 251;
            }
            cfg->prog(cfg, block, i, buffer, PROG) => 0;
        }

        // read
        for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
            cfg->read(cfg, block, i, buffer, READ) => 0;

            for (lfs_off_t j = 0; j < READ; j++) {
                LFS_ASSERT(buffer[j] == (block+i+j) % 251);
            }
        }

        block *= 2;
    }

    // read every power of 2 again
    block = 1;
    while (block < cfg->block_count) {
        // read
        for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
            cfg->read(cfg, block, i, buffer, READ) => 0;

            for (lfs_off_t j = 0; j < READ; j++) {
                LFS_ASSERT(buffer[j] == (block+i+j) % 251);
            }
        }

        block *= 2;
    }
    #line 326 "tests/test_bd.t.a.c"
}

intmax_t __test__test_bd_fibonacci__PROG__0(__attribute__((unused)) void *data) {
    return PROG_SIZE;
}

intmax_t __test__test_bd_fibonacci__READ__0(__attribute__((unused)) void *data) {
    return READ_SIZE;
}

intmax_t __test__test_bd_fibonacci__READ__1(__attribute__((unused)) void *data) {
    return BLOCK_SIZE;
}

const test_define_t __test__test_bd_fibonacci__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [PROG_i                  ] = {__test__test_bd_fibonacci__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_fibonacci__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_fibonacci__PROG__0, NULL},
        [READ_i                  ] = {__test__test_bd_fibonacci__READ__1, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_fibonacci__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_fibonacci__READ__0, NULL},
    },
    {
        [PROG_i                  ] = {__test__test_bd_fibonacci__READ__1, NULL},
        [READ_i                  ] = {__test__test_bd_fibonacci__READ__1, NULL},
    },
};

void __test__test_bd_fibonacci__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_bd_fibonacci
    #line 198 "tests/test_bd.toml"
    uint8_t buffer[lfs_max(READ, PROG)];

    // write/read every fibonacci number on our device
    lfs_block_t block = 1;
    lfs_block_t block_ = 1;
    while (block < cfg->block_count) {
        // write
        cfg->erase(cfg, block) => 0;
        for (lfs_off_t i = 0; i < cfg->block_size; i += PROG) {
            for (lfs_off_t j = 0; j < PROG; j++) {
                buffer[j] = (block+i+j) % 251;
            }
            cfg->prog(cfg, block, i, buffer, PROG) => 0;
        }

        // read
        for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
            cfg->read(cfg, block, i, buffer, READ) => 0;

            for (lfs_off_t j = 0; j < READ; j++) {
                LFS_ASSERT(buffer[j] == (block+i+j) % 251);
            }
        }

        lfs_block_t nblock = block + block_;
        block_ = block;
        block = nblock;
    }

    // read every fibonacci number again
    block = 1;
    block_ = 1;
    while (block < cfg->block_count) {
        // read
        for (lfs_off_t i = 0; i < cfg->block_size; i += READ) {
            cfg->read(cfg, block, i, buffer, READ) => 0;

            for (lfs_off_t j = 0; j < READ; j++) {
                LFS_ASSERT(buffer[j] == (block+i+j) % 251);
            }
        }

        lfs_block_t nblock = block + block_;
        block_ = block;
        block = nblock;
    }
    #line 409 "tests/test_bd.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_bd__suite = {
    .name = "test_bd",
    .path = "tests/test_bd.toml",
    .flags = 0,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+2]){
        [PROG_i                  ] = "PROG",
        [READ_i                  ] = "READ",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+2,
    .cases = (const struct test_case[]){
        {
            .name = "test_bd_one_block",
            .path = "tests/test_bd.toml:7",
            .flags = 0,
            .permutations = 4,
            .defines = (const test_define_t*)__test__test_bd_one_block__defines,
            .run = __test__test_bd_one_block__run,
        },
        {
            .name = "test_bd_two_block",
            .path = "tests/test_bd.toml:32",
            .flags = 0,
            .permutations = 4,
            .defines = (const test_define_t*)__test__test_bd_two_block__defines,
            .run = __test__test_bd_two_block__run,
        },
        {
            .name = "test_bd_last_block",
            .path = "tests/test_bd.toml:90",
            .flags = 0,
            .permutations = 4,
            .defines = (const test_define_t*)__test__test_bd_last_block__defines,
            .run = __test__test_bd_last_block__run,
        },
        {
            .name = "test_bd_powers_of_two",
            .path = "tests/test_bd.toml:148",
            .flags = 0,
            .permutations = 4,
            .defines = (const test_define_t*)__test__test_bd_powers_of_two__defines,
            .run = __test__test_bd_powers_of_two__run,
        },
        {
            .name = "test_bd_fibonacci",
            .path = "tests/test_bd.toml:194",
            .flags = 0,
            .permutations = 4,
            .defines = (const test_define_t*)__test__test_bd_fibonacci__defines,
            .run = __test__test_bd_fibonacci__run,
        },
    },
    .case_count = 5,
};

