// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_truncate.t.a.c -o tests/test_truncate.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_truncate.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_truncate.toml -o tests/test_truncate.t.a.c
//

#include "runners/test_runner.h"

#ifndef CONFIG
#define CONFIG_i                 TEST_IMPLICIT_DEFINE_COUNT+0
#define CONFIG                   TEST_DEFINE(CONFIG_i)
#endif
#ifndef LARGESIZE
#define LARGESIZE_i              TEST_IMPLICIT_DEFINE_COUNT+1
#define LARGESIZE                TEST_DEFINE(LARGESIZE_i)
#endif
#ifndef MEDIUMSIZE
#define MEDIUMSIZE_i             TEST_IMPLICIT_DEFINE_COUNT+2
#define MEDIUMSIZE               TEST_DEFINE(MEDIUMSIZE_i)
#endif
#ifndef SMALLSIZE
#define SMALLSIZE_i              TEST_IMPLICIT_DEFINE_COUNT+3
#define SMALLSIZE                TEST_DEFINE(SMALLSIZE_i)
#endif

intmax_t __test__test_truncate_simple__LARGESIZE__0(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 31;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__2(__attribute__((unused)) void *data) {
    return 33;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__3(__attribute__((unused)) void *data) {
    return 511;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__4(__attribute__((unused)) void *data) {
    return 512;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__5(__attribute__((unused)) void *data) {
    return 513;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__6(__attribute__((unused)) void *data) {
    return 2047;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__7(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_simple__MEDIUMSIZE__8(__attribute__((unused)) void *data) {
    return 2049;
}

intmax_t __test__test_truncate_simple__LARGESIZE__54(__attribute__((unused)) void *data) {
    return 8192;
}

intmax_t __test__test_truncate_simple__LARGESIZE__63(__attribute__((unused)) void *data) {
    return 8193;
}

const test_define_t __test__test_truncate_simple__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_simple__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_simple__MEDIUMSIZE__8, NULL},
    },
};

bool __test__test_truncate_simple__filter(void) {
    return (MEDIUMSIZE < LARGESIZE);
}

void __test__test_truncate_simple__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_simple
    #line 7 "tests/test_truncate.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldynoop",
            LFS_O_WRONLY | LFS_O_CREAT) ,  0);

    uint8_t buffer[1024];
    strcpy((char*)buffer, "hair");
    size_t size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < LARGESIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, LARGESIZE-j))
                ,  lfs_min(size, LARGESIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldynoop", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, MEDIUMSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldynoop", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    size = strlen("hair");
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "hair", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 411 "tests/test_truncate.t.a.c"
}

intmax_t __test__test_truncate_read__LARGESIZE__0(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 31;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__2(__attribute__((unused)) void *data) {
    return 33;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__3(__attribute__((unused)) void *data) {
    return 511;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__4(__attribute__((unused)) void *data) {
    return 512;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__5(__attribute__((unused)) void *data) {
    return 513;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__6(__attribute__((unused)) void *data) {
    return 2047;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__7(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_read__MEDIUMSIZE__8(__attribute__((unused)) void *data) {
    return 2049;
}

intmax_t __test__test_truncate_read__LARGESIZE__54(__attribute__((unused)) void *data) {
    return 8192;
}

intmax_t __test__test_truncate_read__LARGESIZE__63(__attribute__((unused)) void *data) {
    return 8193;
}

const test_define_t __test__test_truncate_read__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_read__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_read__MEDIUMSIZE__8, NULL},
    },
};

bool __test__test_truncate_read__filter(void) {
    return (MEDIUMSIZE < LARGESIZE);
}

void __test__test_truncate_read__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_read
    #line 58 "tests/test_truncate.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldyread",
            LFS_O_WRONLY | LFS_O_CREAT) ,  0);

    uint8_t buffer[1024];
    strcpy((char*)buffer, "hair");
    size_t size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < LARGESIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, LARGESIZE-j))
                ,  lfs_min(size, LARGESIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldyread", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, MEDIUMSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    size = strlen("hair");
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "hair", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldyread", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    size = strlen("hair");
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "hair", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 807 "tests/test_truncate.t.a.c"
}

void __test__test_truncate_write_read__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_write_read
    #line 114 "tests/test_truncate.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "sequence",
            LFS_O_RDWR | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

    uint8_t buffer[1024];
    size_t size = lfs_min(lfs.cfg->cache_size, sizeof(buffer)/2);
    lfs_size_t qsize = size / 4;
    uint8_t *wb = buffer;
    uint8_t *rb = buffer + size;
    for (lfs_off_t j = 0; j < size; ++j) {
        wb[j] = j;
    }

    /* Spread sequence over size */
    __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, wb, size) ,  size);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  size);
    __PRETTY_ASSERT_INT_EQ(lfs_file_tell(&lfs, &file) ,  size);

    __PRETTY_ASSERT_INT_EQ(lfs_file_seek(&lfs, &file, 0, LFS_SEEK_SET) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_tell(&lfs, &file) ,  0);

    /* Chop off the last quarter */
    lfs_size_t trunc = size - qsize;
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, trunc) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_tell(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  trunc);

    /* Read should produce first 3/4 */
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, rb, size) ,  trunc);
    __PRETTY_ASSERT_MEM_EQ(rb, wb, trunc);

    /* Move to 1/4 */
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  trunc);
    __PRETTY_ASSERT_INT_EQ(lfs_file_seek(&lfs, &file, qsize, LFS_SEEK_SET) ,  qsize);
    __PRETTY_ASSERT_INT_EQ(lfs_file_tell(&lfs, &file) ,  qsize);

    /* Chop to 1/2 */
    trunc -= qsize;
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, trunc) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_tell(&lfs, &file) ,  qsize);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  trunc);

    /* Read should produce second quarter */
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, rb, size) ,  trunc - qsize);
    __PRETTY_ASSERT_MEM_EQ(rb, wb + qsize, trunc - qsize);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 864 "tests/test_truncate.t.a.c"
}

intmax_t __test__test_truncate_write__LARGESIZE__0(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 31;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__2(__attribute__((unused)) void *data) {
    return 33;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__3(__attribute__((unused)) void *data) {
    return 511;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__4(__attribute__((unused)) void *data) {
    return 512;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__5(__attribute__((unused)) void *data) {
    return 513;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__6(__attribute__((unused)) void *data) {
    return 2047;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__7(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_write__MEDIUMSIZE__8(__attribute__((unused)) void *data) {
    return 2049;
}

intmax_t __test__test_truncate_write__LARGESIZE__54(__attribute__((unused)) void *data) {
    return 8192;
}

intmax_t __test__test_truncate_write__LARGESIZE__63(__attribute__((unused)) void *data) {
    return 8193;
}

const test_define_t __test__test_truncate_write__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__54, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__LARGESIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__2, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__3, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__4, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__5, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__6, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__7, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_write__LARGESIZE__63, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_write__MEDIUMSIZE__8, NULL},
    },
};

bool __test__test_truncate_write__filter(void) {
    return (MEDIUMSIZE < LARGESIZE);
}

void __test__test_truncate_write__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_write
    #line 173 "tests/test_truncate.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldywrite",
            LFS_O_WRONLY | LFS_O_CREAT) ,  0);

    uint8_t buffer[1024];
    strcpy((char*)buffer, "hair");
    size_t size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < LARGESIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, LARGESIZE-j))
                ,  lfs_min(size, LARGESIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldywrite", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);

    /* truncate */
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, MEDIUMSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    /* and write */
    strcpy((char*)buffer, "bald");
    size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldywrite", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    size = strlen("bald");
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "bald", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1262 "tests/test_truncate.t.a.c"
}

intmax_t __test__test_truncate_reentrant_write__LARGESIZE__0(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 0;
}

intmax_t __test__test_truncate_reentrant_write__SMALLSIZE__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_truncate_reentrant_write__SMALLSIZE__1(__attribute__((unused)) void *data) {
    return 512;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__2(__attribute__((unused)) void *data) {
    return 3;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__6(__attribute__((unused)) void *data) {
    return 5;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__8(__attribute__((unused)) void *data) {
    return 31;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__10(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__12(__attribute__((unused)) void *data) {
    return 33;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__14(__attribute__((unused)) void *data) {
    return 511;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__18(__attribute__((unused)) void *data) {
    return 513;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__20(__attribute__((unused)) void *data) {
    return 1023;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__22(__attribute__((unused)) void *data) {
    return 1024;
}

intmax_t __test__test_truncate_reentrant_write__MEDIUMSIZE__24(__attribute__((unused)) void *data) {
    return 1025;
}

const test_define_t __test__test_truncate_reentrant_write__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__2, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__2, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__6, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__6, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__8, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__8, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__10, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__10, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__12, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__12, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__14, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__14, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__18, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__18, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__20, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__20, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__22, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__22, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__24, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__0, NULL},
    },
    {
        [LARGESIZE_i             ] = {__test__test_truncate_reentrant_write__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_reentrant_write__MEDIUMSIZE__24, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_reentrant_write__SMALLSIZE__1, NULL},
    },
};

void __test__test_truncate_reentrant_write__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_reentrant_write
    #line 235 "tests/test_truncate.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }
    lfs_file_t file;
    err = lfs_file_open(&lfs, &file, "baldy", LFS_O_RDONLY);
    __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_NOENT, true);
    if (!err) {
        size_t size = lfs_file_size(&lfs, &file);
        __PRETTY_ASSERT_BOOL_EQ(size == 0 ||
                size == (size_t)LARGESIZE ||
                size == (size_t)MEDIUMSIZE ||
                size == (size_t)SMALLSIZE, true);
        for (lfs_off_t j = 0; j < size; j += 4) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(4, size-j))
                    ,  lfs_min(4, size-j));
            __PRETTY_ASSERT_BOOL_EQ(memcmp(buffer, "hair", lfs_min(4, size-j)) == 0 ||
                   memcmp(buffer, "bald", lfs_min(4, size-j)) == 0 ||
                   memcmp(buffer, "comb", lfs_min(4, size-j)) == 0, true);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldy",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  0);
    uint8_t buffer[1024];
    strcpy((char*)buffer, "hair");
    size_t size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < LARGESIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, LARGESIZE-j))
                ,  lfs_min(size, LARGESIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldy", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  LARGESIZE);
    /* truncate */
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, MEDIUMSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);
    /* and write */
    strcpy((char*)buffer, "bald");
    size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldy", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, SMALLSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  SMALLSIZE);
    strcpy((char*)buffer, "comb");
    size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < SMALLSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, SMALLSIZE-j))
                ,  lfs_min(size, SMALLSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  SMALLSIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1525 "tests/test_truncate.t.a.c"
}

intmax_t __test__test_truncate_aggressive__CONFIG__0(__attribute__((unused)) void *data) {
    return (0);
}

intmax_t __test__test_truncate_aggressive__LARGESIZE__0(__attribute__((unused)) void *data) {
    return 8192;
}

intmax_t __test__test_truncate_aggressive__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_aggressive__SMALLSIZE__0(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_aggressive__CONFIG__1(__attribute__((unused)) void *data) {
    return (1);
}

intmax_t __test__test_truncate_aggressive__CONFIG__2(__attribute__((unused)) void *data) {
    return (2);
}

intmax_t __test__test_truncate_aggressive__CONFIG__3(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_truncate_aggressive__CONFIG__4(__attribute__((unused)) void *data) {
    return (4);
}

intmax_t __test__test_truncate_aggressive__CONFIG__5(__attribute__((unused)) void *data) {
    return (5);
}

const test_define_t __test__test_truncate_aggressive__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__0, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__1, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__2, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__3, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__4, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
    {
        [CONFIG_i                ] = {__test__test_truncate_aggressive__CONFIG__5, NULL},
        [LARGESIZE_i             ] = {__test__test_truncate_aggressive__LARGESIZE__0, NULL},
        [MEDIUMSIZE_i            ] = {__test__test_truncate_aggressive__MEDIUMSIZE__0, NULL},
        [SMALLSIZE_i             ] = {__test__test_truncate_aggressive__SMALLSIZE__0, NULL},
    },
};

void __test__test_truncate_aggressive__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_aggressive
    #line 312 "tests/test_truncate.toml"
    lfs_t lfs;
    #define COUNT 5
    const struct {
        lfs_off_t startsizes[COUNT];
        lfs_off_t startseeks[COUNT];
        lfs_off_t hotsizes[COUNT];
        lfs_off_t coldsizes[COUNT];
    } configs[] = {
        // cold shrinking
        {{2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE}},
        // cold expanding
        {{2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE}},
        // warm shrinking truncate
        {{2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE},
         {          0,           0,           0,           0,           0}},
        // warm expanding truncate
        {{          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE},
         {          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE}},
        // mid-file shrinking truncate
        {{2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {  LARGESIZE,   LARGESIZE,   LARGESIZE,   LARGESIZE,   LARGESIZE},
         {          0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE, 2*LARGESIZE},
         {          0,           0,           0,           0,           0}},
        // mid-file expanding truncate
        {{          0,   SMALLSIZE,   MEDIUMSIZE,  LARGESIZE, 2*LARGESIZE},
         {          0,           0,   SMALLSIZE,  MEDIUMSIZE,   LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE},
         {2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE, 2*LARGESIZE}},
    };

    const lfs_off_t *startsizes = configs[CONFIG].startsizes;
    const lfs_off_t *startseeks = configs[CONFIG].startseeks;
    const lfs_off_t *hotsizes   = configs[CONFIG].hotsizes;
    const lfs_off_t *coldsizes  = configs[CONFIG].coldsizes;

    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);

    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hairyhead%d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

        uint8_t buffer[1024];
        strcpy((char*)buffer, "hair");
        size_t size = strlen((char*)buffer);
        for (lfs_off_t j = 0; j < startsizes[i]; j += size) {
            __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, size) ,  size);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  startsizes[i]);

        if (startseeks[i] != startsizes[i]) {
            __PRETTY_ASSERT_INT_EQ(lfs_file_seek(&lfs, &file,
                    startseeks[i], LFS_SEEK_SET) ,  startseeks[i]);
        }

        __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, hotsizes[i]) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  hotsizes[i]);

        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);

    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hairyhead%d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDWR) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  hotsizes[i]);

        size_t size = strlen("hair");
        lfs_off_t j = 0;
        for (; j < startsizes[i] && j < hotsizes[i]; j += size) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  size);
            __PRETTY_ASSERT_MEM_EQ(buffer, "hair", size);
        }

        for (; j < hotsizes[i]; j += size) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  size);
            __PRETTY_ASSERT_MEM_EQ(buffer, "\0\0\0\0", size);
        }

        __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, coldsizes[i]) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  coldsizes[i]);

        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);

    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hairyhead%d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  coldsizes[i]);

        size_t size = strlen("hair");
        lfs_off_t j = 0;
        for (; j < startsizes[i] && j < hotsizes[i] && j < coldsizes[i];
                j += size) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  size);
            __PRETTY_ASSERT_MEM_EQ(buffer, "hair", size);
        }

        for (; j < coldsizes[i]; j += size) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  size);
            __PRETTY_ASSERT_MEM_EQ(buffer, "\0\0\0\0", size);
        }

        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1741 "tests/test_truncate.t.a.c"
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__0(__attribute__((unused)) void *data) {
    return 32;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__1(__attribute__((unused)) void *data) {
    return 33;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__2(__attribute__((unused)) void *data) {
    return 512;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__3(__attribute__((unused)) void *data) {
    return 513;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__4(__attribute__((unused)) void *data) {
    return 2048;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__5(__attribute__((unused)) void *data) {
    return 2049;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__6(__attribute__((unused)) void *data) {
    return 8192;
}

intmax_t __test__test_truncate_nop__MEDIUMSIZE__7(__attribute__((unused)) void *data) {
    return 8193;
}

const test_define_t __test__test_truncate_nop__defines[][TEST_IMPLICIT_DEFINE_COUNT+4] = {
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__0, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__1, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__2, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__3, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__4, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__5, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__6, NULL},
    },
    {
        [MEDIUMSIZE_i            ] = {__test__test_truncate_nop__MEDIUMSIZE__7, NULL},
    },
};

void __test__test_truncate_nop__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_truncate_nop
    #line 453 "tests/test_truncate.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldynoop",
            LFS_O_RDWR | LFS_O_CREAT) ,  0);

    uint8_t buffer[1024];
    strcpy((char*)buffer, "hair");
    size_t size = strlen((char*)buffer);
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));

        // this truncate should do nothing
        __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, j+lfs_min(size, MEDIUMSIZE-j)) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    __PRETTY_ASSERT_INT_EQ(lfs_file_seek(&lfs, &file, 0, LFS_SEEK_SET) ,  0);
    // should do nothing again
    __PRETTY_ASSERT_INT_EQ(lfs_file_truncate(&lfs, &file, MEDIUMSIZE) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);

    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "hair", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // still there after reboot?
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "baldynoop", LFS_O_RDWR) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_size(&lfs, &file) ,  MEDIUMSIZE);
    for (lfs_off_t j = 0; j < MEDIUMSIZE; j += size) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, lfs_min(size, MEDIUMSIZE-j))
                ,  lfs_min(size, MEDIUMSIZE-j));
        __PRETTY_ASSERT_MEM_EQ(buffer, "hair", lfs_min(size, MEDIUMSIZE-j));
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, size) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1852 "tests/test_truncate.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_truncate__suite = {
    .name = "test_truncate",
    .path = "tests/test_truncate.toml",
    .flags = TEST_REENTRANT,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+4]){
        [CONFIG_i                ] = "CONFIG",
        [LARGESIZE_i             ] = "LARGESIZE",
        [MEDIUMSIZE_i            ] = "MEDIUMSIZE",
        [SMALLSIZE_i             ] = "SMALLSIZE",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+4,
    .cases = (const struct test_case[]){
        {
            .name = "test_truncate_simple",
            .path = "tests/test_truncate.toml:2",
            .flags = 0,
            .permutations = 72,
            .defines = (const test_define_t*)__test__test_truncate_simple__defines,
            .filter = __test__test_truncate_simple__filter,
            .run = __test__test_truncate_simple__run,
        },
        {
            .name = "test_truncate_read",
            .path = "tests/test_truncate.toml:53",
            .flags = 0,
            .permutations = 72,
            .defines = (const test_define_t*)__test__test_truncate_read__defines,
            .filter = __test__test_truncate_read__filter,
            .run = __test__test_truncate_read__run,
        },
        {
            .name = "test_truncate_write_read",
            .path = "tests/test_truncate.toml:112",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_truncate_write_read__run,
        },
        {
            .name = "test_truncate_write",
            .path = "tests/test_truncate.toml:168",
            .flags = 0,
            .permutations = 72,
            .defines = (const test_define_t*)__test__test_truncate_write__defines,
            .filter = __test__test_truncate_write__filter,
            .run = __test__test_truncate_write__run,
        },
        {
            .name = "test_truncate_reentrant_write",
            .path = "tests/test_truncate.toml:229",
            .flags = TEST_REENTRANT,
            .permutations = 26,
            .defines = (const test_define_t*)__test__test_truncate_reentrant_write__defines,
            .run = __test__test_truncate_reentrant_write__run,
        },
        {
            .name = "test_truncate_aggressive",
            .path = "tests/test_truncate.toml:306",
            .flags = 0,
            .permutations = 6,
            .defines = (const test_define_t*)__test__test_truncate_aggressive__defines,
            .run = __test__test_truncate_aggressive__run,
        },
        {
            .name = "test_truncate_nop",
            .path = "tests/test_truncate.toml:450",
            .flags = 0,
            .permutations = 8,
            .defines = (const test_define_t*)__test__test_truncate_nop__defines,
            .run = __test__test_truncate_nop__run,
        },
    },
    .case_count = 7,
};

