// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_interspersed.t.a.c -o tests/test_interspersed.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_interspersed.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_interspersed.toml -o tests/test_interspersed.t.a.c
//

#include "runners/test_runner.h"

#ifndef FILES
#define FILES_i                  TEST_IMPLICIT_DEFINE_COUNT+0
#define FILES                    TEST_DEFINE(FILES_i)
#endif
#ifndef SIZE
#define SIZE_i                   TEST_IMPLICIT_DEFINE_COUNT+1
#define SIZE                     TEST_DEFINE(SIZE_i)
#endif

intmax_t __test__test_interspersed_files__FILES__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_interspersed_files__SIZE__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_interspersed_files__SIZE__1(__attribute__((unused)) void *data) {
    return 100;
}

intmax_t __test__test_interspersed_files__FILES__4(__attribute__((unused)) void *data) {
    return 26;
}

const test_define_t __test__test_interspersed_files__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [FILES_i                 ] = {__test__test_interspersed_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_files__SIZE__1, NULL},
    },
};

void __test__test_interspersed_files__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_interspersed_files
    #line 6 "tests/test_interspersed.toml"
    lfs_t lfs;
    lfs_file_t files[FILES];
    const char alphas[] = "abcdefghijklmnopqrstuvwxyz";
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[j], path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
    }

    for (int i = 0; i < SIZE; i++) {
        for (int j = 0; j < FILES; j++) {
            __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[j], &alphas[j], 1) ,  1);
        }
    }

    for (int j = 0; j < FILES; j++) {
        lfs_file_close(&lfs, &files[j]);
    }

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_INT_EQ(info.size , SIZE);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[j], path, LFS_O_RDONLY) ,  0);
    }

    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < FILES; j++) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &files[j], buffer, 1) ,  1);
            __PRETTY_ASSERT_INT_EQ(buffer[0] , alphas[j]);
        }
    }

    for (int j = 0; j < FILES; j++) {
        lfs_file_close(&lfs, &files[j]);
    }
    
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 125 "tests/test_interspersed.t.a.c"
}

intmax_t __test__test_interspersed_remove_files__FILES__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_interspersed_remove_files__SIZE__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_interspersed_remove_files__SIZE__1(__attribute__((unused)) void *data) {
    return 100;
}

intmax_t __test__test_interspersed_remove_files__FILES__4(__attribute__((unused)) void *data) {
    return 26;
}

const test_define_t __test__test_interspersed_remove_files__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_remove_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_remove_files__SIZE__1, NULL},
    },
};

void __test__test_interspersed_remove_files__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_interspersed_remove_files
    #line 73 "tests/test_interspersed.toml"
    lfs_t lfs;
    const char alphas[] = "abcdefghijklmnopqrstuvwxyz";
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
        for (int i = 0; i < SIZE; i++) {
            __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, &alphas[j], 1) ,  1);
        }
        lfs_file_close(&lfs, &file);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "zzz", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    for (int j = 0; j < FILES; j++) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, (const void*)"~", 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_file_sync(&lfs, &file) ,  0);

        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }
    lfs_file_close(&lfs, &file);

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "zzz");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
    __PRETTY_ASSERT_INT_EQ(info.size , FILES);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "zzz", LFS_O_RDONLY) ,  0);
    for (int i = 0; i < FILES; i++) {
        uint8_t buffer[1024];
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(buffer[0] , '~');
    }
    lfs_file_close(&lfs, &file);
    
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 229 "tests/test_interspersed.t.a.c"
}

intmax_t __test__test_interspersed_remove_inconveniently__SIZE__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_interspersed_remove_inconveniently__SIZE__1(__attribute__((unused)) void *data) {
    return 100;
}

const test_define_t __test__test_interspersed_remove_inconveniently__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [SIZE_i                  ] = {__test__test_interspersed_remove_inconveniently__SIZE__0, NULL},
    },
    {
        [SIZE_i                  ] = {__test__test_interspersed_remove_inconveniently__SIZE__1, NULL},
    },
};

void __test__test_interspersed_remove_inconveniently__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_interspersed_remove_inconveniently
    #line 133 "tests/test_interspersed.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t files[3];
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[0], "e", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[1], "f", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[2], "g", LFS_O_WRONLY | LFS_O_CREAT) ,  0);

    for (int i = 0; i < SIZE/2; i++) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[0], (const void*)"e", 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[1], (const void*)"f", 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[2], (const void*)"g", 1) ,  1);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "f") ,  0);

    for (int i = 0; i < SIZE/2; i++) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[0], (const void*)"e", 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[1], (const void*)"f", 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[2], (const void*)"g", 1) ,  1);
    }

    lfs_file_close(&lfs, &files[0]);
    lfs_file_close(&lfs, &files[1]);
    lfs_file_close(&lfs, &files[2]);

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "e");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
    __PRETTY_ASSERT_INT_EQ(info.size , SIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "g");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
    __PRETTY_ASSERT_INT_EQ(info.size , SIZE);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[0], "e", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[1], "g", LFS_O_RDONLY) ,  0);
    for (int i = 0; i < SIZE; i++) {
        uint8_t buffer[1024];
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &files[0], buffer, 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(buffer[0] , 'e');
        __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &files[1], buffer, 1) ,  1);
        __PRETTY_ASSERT_INT_EQ(buffer[0] , 'g');
    }
    lfs_file_close(&lfs, &files[0]);
    lfs_file_close(&lfs, &files[1]);
    
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 311 "tests/test_interspersed.t.a.c"
}

intmax_t __test__test_interspersed_reentrant_files__FILES__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_interspersed_reentrant_files__SIZE__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_interspersed_reentrant_files__SIZE__1(__attribute__((unused)) void *data) {
    return 100;
}

intmax_t __test__test_interspersed_reentrant_files__FILES__4(__attribute__((unused)) void *data) {
    return 26;
}

const test_define_t __test__test_interspersed_reentrant_files__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__FILES__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__SIZE__0, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__1, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__0, NULL},
    },
    {
        [FILES_i                 ] = {__test__test_interspersed_reentrant_files__FILES__4, NULL},
        [SIZE_i                  ] = {__test__test_interspersed_reentrant_files__SIZE__1, NULL},
    },
};

void __test__test_interspersed_reentrant_files__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_interspersed_reentrant_files
    #line 199 "tests/test_interspersed.toml"
    lfs_t lfs;
    lfs_file_t files[FILES];
    const char alphas[] = "abcdefghijklmnopqrstuvwxyz";

    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }

    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[j], path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_APPEND) ,  0);
    }

    for (int i = 0; i < SIZE; i++) {
        for (int j = 0; j < FILES; j++) {
            lfs_ssize_t size = lfs_file_size(&lfs, &files[j]);
            __PRETTY_ASSERT_INT_GE(size , 0);
            if ((int)size <= i) {
                __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &files[j], &alphas[j], 1) ,  1);
                __PRETTY_ASSERT_INT_EQ(lfs_file_sync(&lfs, &files[j]) ,  0);
            }
        }
    }

    for (int j = 0; j < FILES; j++) {
        lfs_file_close(&lfs, &files[j]);
    }

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_INT_EQ(info.size , SIZE);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int j = 0; j < FILES; j++) {
        char path[1024];
        sprintf(path, "%c", alphas[j]);
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &files[j], path, LFS_O_RDONLY) ,  0);
    }

    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < FILES; j++) {
            uint8_t buffer[1024];
            __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &files[j], buffer, 1) ,  1);
            __PRETTY_ASSERT_INT_EQ(buffer[0] , alphas[j]);
        }
    }

    for (int j = 0; j < FILES; j++) {
        lfs_file_close(&lfs, &files[j]);
    }
    
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 431 "tests/test_interspersed.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_interspersed__suite = {
    .name = "test_interspersed",
    .path = "tests/test_interspersed.toml",
    .flags = TEST_REENTRANT,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+2]){
        [FILES_i                 ] = "FILES",
        [SIZE_i                  ] = "SIZE",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+2,
    .cases = (const struct test_case[]){
        {
            .name = "test_interspersed_files",
            .path = "tests/test_interspersed.toml:2",
            .flags = 0,
            .permutations = 6,
            .defines = (const test_define_t*)__test__test_interspersed_files__defines,
            .run = __test__test_interspersed_files__run,
        },
        {
            .name = "test_interspersed_remove_files",
            .path = "tests/test_interspersed.toml:69",
            .flags = 0,
            .permutations = 6,
            .defines = (const test_define_t*)__test__test_interspersed_remove_files__defines,
            .run = __test__test_interspersed_remove_files__run,
        },
        {
            .name = "test_interspersed_remove_inconveniently",
            .path = "tests/test_interspersed.toml:130",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_interspersed_remove_inconveniently__defines,
            .run = __test__test_interspersed_remove_inconveniently__run,
        },
        {
            .name = "test_interspersed_reentrant_files",
            .path = "tests/test_interspersed.toml:194",
            .flags = TEST_REENTRANT,
            .permutations = 6,
            .defines = (const test_define_t*)__test__test_interspersed_reentrant_files__defines,
            .run = __test__test_interspersed_reentrant_files__run,
        },
    },
    .case_count = 4,
};

