// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_attrs.t.a.c -o tests/test_attrs.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_attrs.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_attrs.toml -o tests/test_attrs.t.a.c
//

#include "runners/test_runner.h"

void __test__test_attrs_get_set__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_attrs_get_set
    #line 3 "tests/test_attrs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "hello") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hello", strlen("hello")) ,  strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    uint8_t buffer[1024];
    memset(buffer, 0, sizeof(buffer));
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'A', "aaaa",   4) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'B', "bbbbbb", 6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'C', "ccccc",  5) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  6);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "bbbbbb", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'B', "", 0) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "\0\0\0\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_removeattr(&lfs, "hello", 'B') ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  LFS_ERR_NOATTR);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "\0\0\0\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'B', "dddddd", 6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  6);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "dddddd", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'B', "eee", 3) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  3);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "eee\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'A', buffer, LFS_ATTR_MAX+1) ,  LFS_ERR_NOSPC);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello", 'B', "fffffffff", 9) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  6) ,  9);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+10, 5) ,  5);

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    memset(buffer, 0, sizeof(buffer));
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'B', buffer+4,  9) ,  9);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello", 'C', buffer+13, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "fffffffff", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+13, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, sizeof(buffer)) ,  strlen("hello"));
    __PRETTY_ASSERT_MEM_EQ(buffer, "hello", strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 89 "tests/test_attrs.t.a.c"
}

void __test__test_attrs_get_set_root__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_attrs_get_set_root
    #line 84 "tests/test_attrs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "hello") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hello", strlen("hello")) ,  strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    uint8_t buffer[1024];
    memset(buffer, 0, sizeof(buffer));
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'A', "aaaa",   4) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'B', "bbbbbb", 6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'C', "ccccc",  5) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  6);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "bbbbbb", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'B', "", 0) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "\0\0\0\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_removeattr(&lfs, "/", 'B') ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  LFS_ERR_NOATTR);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "\0\0\0\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'B', "dddddd", 6) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  6);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "dddddd", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'B', "eee", 3) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  3);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "eee\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'A', buffer, LFS_ATTR_MAX+1) ,  LFS_ERR_NOSPC);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "/", 'B', "fffffffff", 9) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  6) ,  9);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+10, 5) ,  5);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    memset(buffer, 0, sizeof(buffer));
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'A', buffer,    4) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'B', buffer+4,  9) ,  9);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "/", 'C', buffer+13, 5) ,  5);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "fffffffff", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+13, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, sizeof(buffer)) ,  strlen("hello"));
    __PRETTY_ASSERT_MEM_EQ(buffer, "hello", strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 171 "tests/test_attrs.t.a.c"
}

void __test__test_attrs_get_set_file__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_attrs_get_set_file
    #line 164 "tests/test_attrs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "hello") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hello", strlen("hello")) ,  strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    uint8_t buffer[1024];
    memset(buffer, 0, sizeof(buffer));
    struct lfs_attr attrs1[] = {
        {'A', buffer,    4},
        {'B', buffer+4,  6},
        {'C', buffer+10, 5},
    };
    struct lfs_file_config cfg1 = {.attrs=attrs1, .attr_count=3};

    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1) ,  0);
    memcpy(buffer,    "aaaa",   4);
    memcpy(buffer+4,  "bbbbbb", 6);
    memcpy(buffer+10, "ccccc",  5);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    memset(buffer, 0, 15);
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "bbbbbb", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    attrs1[1].size = 0;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    memset(buffer, 0, 15);
    attrs1[1].size = 6;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "\0\0\0\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    attrs1[1].size = 6;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1) ,  0);
    memcpy(buffer+4,  "dddddd", 6);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    memset(buffer, 0, 15);
    attrs1[1].size = 6;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "dddddd", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    attrs1[1].size = 3;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1) ,  0);
    memcpy(buffer+4,  "eee", 3);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    memset(buffer, 0, 15);
    attrs1[1].size = 6;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "eee\0\0\0", 6);
    __PRETTY_ASSERT_MEM_EQ(buffer+10, "ccccc", 5);

    attrs1[0].size = LFS_ATTR_MAX+1;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1)
        ,  LFS_ERR_NOSPC);

    struct lfs_attr attrs2[] = {
        {'A', buffer,    4},
        {'B', buffer+4,  9},
        {'C', buffer+13, 5},
    };
    struct lfs_file_config cfg2 = {.attrs=attrs2, .attr_count=3};
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDWR, &cfg2) ,  0);
    memcpy(buffer+4,  "fffffffff", 9);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    attrs1[0].size = 4;
    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg1) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    memset(buffer, 0, sizeof(buffer));
    struct lfs_attr attrs3[] = {
        {'A', buffer,    4},
        {'B', buffer+4,  9},
        {'C', buffer+13, 5},
    };
    struct lfs_file_config cfg3 = {.attrs=attrs3, .attr_count=3};

    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_RDONLY, &cfg3) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_MEM_EQ(buffer, "aaaa", 4);
    __PRETTY_ASSERT_MEM_EQ(buffer+4, "fffffffff", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+13, "ccccc", 5);

    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_RDONLY) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, buffer, sizeof(buffer)) ,  strlen("hello"));
    __PRETTY_ASSERT_MEM_EQ(buffer, "hello", strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 283 "tests/test_attrs.t.a.c"
}

void __test__test_attrs_deferred_file__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_attrs_deferred_file
    #line 274 "tests/test_attrs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "hello") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "hello/hello", LFS_O_WRONLY | LFS_O_CREAT) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hello", strlen("hello")) ,  strlen("hello"));
    lfs_file_close(&lfs, &file);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello/hello", 'B', "fffffffff",  9) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_setattr(&lfs, "hello/hello", 'C', "ccccc",      5) ,  0);

    uint8_t buffer[1024];
    memset(buffer, 0, sizeof(buffer));
    struct lfs_attr attrs1[] = {
        {'B', "gggg", 4},
        {'C', "",     0},
        {'D', "hhhh", 4},
    };
    struct lfs_file_config cfg1 = {.attrs=attrs1, .attr_count=3};

    __PRETTY_ASSERT_INT_EQ(lfs_file_opencfg(&lfs, &file, "hello/hello", LFS_O_WRONLY, &cfg1) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'B', buffer,    9) ,  9);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'C', buffer+9,  9) ,  5);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'D', buffer+18, 9) ,  LFS_ERR_NOATTR);
    __PRETTY_ASSERT_MEM_EQ(buffer, "fffffffff", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+9, "ccccc\0\0\0\0", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+18, "\0\0\0\0\0\0\0\0\0", 9);

    __PRETTY_ASSERT_INT_EQ(lfs_file_sync(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'B', buffer,    9) ,  4);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'C', buffer+9,  9) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_getattr(&lfs, "hello/hello", 'D', buffer+18, 9) ,  4);
    __PRETTY_ASSERT_MEM_EQ(buffer, "gggg\0\0\0\0\0", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+9, "\0\0\0\0\0\0\0\0\0", 9);
    __PRETTY_ASSERT_MEM_EQ(buffer+18, "hhhh\0\0\0\0\0", 9);

    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 331 "tests/test_attrs.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_attrs__suite = {
    .name = "test_attrs",
    .path = "tests/test_attrs.toml",
    .flags = 0,
    .cases = (const struct test_case[]){
        {
            .name = "test_attrs_get_set",
            .path = "tests/test_attrs.toml:1",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_attrs_get_set__run,
        },
        {
            .name = "test_attrs_get_set_root",
            .path = "tests/test_attrs.toml:82",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_attrs_get_set_root__run,
        },
        {
            .name = "test_attrs_get_set_file",
            .path = "tests/test_attrs.toml:162",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_attrs_get_set_file__run,
        },
        {
            .name = "test_attrs_deferred_file",
            .path = "tests/test_attrs.toml:272",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_attrs_deferred_file__run,
        },
    },
    .case_count = 4,
};

