// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_relocations.toml -o tests/test_relocations.t.a.c
//

#include "runners/test_runner.h"

#ifndef BLOCK_CYCLES
#define BLOCK_CYCLES_i           TEST_IMPLICIT_DEFINE_COUNT+0
#define BLOCK_CYCLES             TEST_DEFINE(BLOCK_CYCLES_i)
#endif
#ifndef COUNT
#define COUNT_i                  TEST_IMPLICIT_DEFINE_COUNT+1
#define COUNT                    TEST_DEFINE(COUNT_i)
#endif
#ifndef CYCLES
#define CYCLES_i                 TEST_IMPLICIT_DEFINE_COUNT+2
#define CYCLES                   TEST_DEFINE(CYCLES_i)
#endif
#ifndef DEPTH
#define DEPTH_i                  TEST_IMPLICIT_DEFINE_COUNT+3
#define DEPTH                    TEST_DEFINE(DEPTH_i)
#endif
#ifndef FILES
#define FILES_i                  TEST_IMPLICIT_DEFINE_COUNT+4
#define FILES                    TEST_DEFINE(FILES_i)
#endif
#ifndef ITERATIONS
#define ITERATIONS_i             TEST_IMPLICIT_DEFINE_COUNT+5
#define ITERATIONS               TEST_DEFINE(ITERATIONS_i)
#endif

intmax_t __test__test_relocations_dangling_split_dir__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 8;
}

intmax_t __test__test_relocations_dangling_split_dir__COUNT__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_relocations_dangling_split_dir__ITERATIONS__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_dangling_split_dir__BLOCK_CYCLES__1(__attribute__((unused)) void *data) {
    return 1;
}

const test_define_t __test__test_relocations_dangling_split_dir__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_dangling_split_dir__BLOCK_CYCLES__0, NULL},
        [COUNT_i                 ] = {__test__test_relocations_dangling_split_dir__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_dangling_split_dir__ITERATIONS__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_dangling_split_dir__BLOCK_CYCLES__1, NULL},
        [COUNT_i                 ] = {__test__test_relocations_dangling_split_dir__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_dangling_split_dir__ITERATIONS__0, NULL},
    },
};

void __test__test_relocations_dangling_split_dir__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_dangling_split_dir
    #line 7 "tests/test_relocations.toml"
    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    // fill up filesystem so only ~16 blocks are left
    lfs_mount(&lfs, cfg) => 0;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, "padding", LFS_O_CREAT | LFS_O_WRONLY) => 0;
    uint8_t buffer[512];
    memset(buffer, 0, 512);
    while (BLOCK_COUNT - lfs_fs_size(&lfs) > 16) {
        lfs_file_write(&lfs, &file, buffer, 512) => 512;
    }
    lfs_file_close(&lfs, &file) => 0;
    // make a child dir to use in bounded space
    lfs_mkdir(&lfs, "child") => 0;
    lfs_unmount(&lfs) => 0;

    lfs_mount(&lfs, cfg) => 0;
    for (unsigned j = 0; j < ITERATIONS; j++) {
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_file_open(&lfs, &file, path, LFS_O_CREAT | LFS_O_WRONLY) => 0;
            lfs_file_close(&lfs, &file) => 0;
        }

        lfs_dir_t dir;
        struct lfs_info info;
        lfs_dir_open(&lfs, &dir, "child") => 0;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            lfs_dir_read(&lfs, &dir, &info) => 1;
            strcmp(info.name, path) => 0;
        }
        lfs_dir_read(&lfs, &dir, &info) => 0;
        lfs_dir_close(&lfs, &dir) => 0;

        if (j == (unsigned)ITERATIONS-1) {
            break;
        }

        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_remove(&lfs, path) => 0;
        }
    }
    lfs_unmount(&lfs) => 0;

    lfs_mount(&lfs, cfg) => 0;
    lfs_dir_t dir;
    struct lfs_info info;
    lfs_dir_open(&lfs, &dir, "child") => 0;
    lfs_dir_read(&lfs, &dir, &info) => 1;
    lfs_dir_read(&lfs, &dir, &info) => 1;
    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "test%03d_loooooooooooooooooong_name", i);
        lfs_dir_read(&lfs, &dir, &info) => 1;
        strcmp(info.name, path) => 0;
    }
    lfs_dir_read(&lfs, &dir, &info) => 0;
    lfs_dir_close(&lfs, &dir) => 0;
    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
        lfs_remove(&lfs, path) => 0;
    }
    lfs_unmount(&lfs) => 0;
    #line 137 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_outdated_head__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 8;
}

intmax_t __test__test_relocations_outdated_head__COUNT__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_relocations_outdated_head__ITERATIONS__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_outdated_head__BLOCK_CYCLES__1(__attribute__((unused)) void *data) {
    return 1;
}

const test_define_t __test__test_relocations_outdated_head__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_outdated_head__BLOCK_CYCLES__0, NULL},
        [COUNT_i                 ] = {__test__test_relocations_outdated_head__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_outdated_head__ITERATIONS__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_outdated_head__BLOCK_CYCLES__1, NULL},
        [COUNT_i                 ] = {__test__test_relocations_outdated_head__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_outdated_head__ITERATIONS__0, NULL},
    },
};

void __test__test_relocations_outdated_head__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_outdated_head
    #line 85 "tests/test_relocations.toml"
    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    // fill up filesystem so only ~16 blocks are left
    lfs_mount(&lfs, cfg) => 0;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, "padding", LFS_O_CREAT | LFS_O_WRONLY) => 0;
    uint8_t buffer[512];
    memset(buffer, 0, 512);
    while (BLOCK_COUNT - lfs_fs_size(&lfs) > 16) {
        lfs_file_write(&lfs, &file, buffer, 512) => 512;
    }
    lfs_file_close(&lfs, &file) => 0;
    // make a child dir to use in bounded space
    lfs_mkdir(&lfs, "child") => 0;
    lfs_unmount(&lfs) => 0;

    lfs_mount(&lfs, cfg) => 0;
    for (unsigned j = 0; j < ITERATIONS; j++) {
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_file_open(&lfs, &file, path, LFS_O_CREAT | LFS_O_WRONLY) => 0;
            lfs_file_close(&lfs, &file) => 0;
        }

        lfs_dir_t dir;
        struct lfs_info info;
        lfs_dir_open(&lfs, &dir, "child") => 0;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            lfs_dir_read(&lfs, &dir, &info) => 1;
            strcmp(info.name, path) => 0;
            info.size => 0;

            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_file_open(&lfs, &file, path, LFS_O_WRONLY) => 0;
            lfs_file_write(&lfs, &file, "hi", 2) => 2;
            lfs_file_close(&lfs, &file) => 0;
        }
        lfs_dir_read(&lfs, &dir, &info) => 0;

        lfs_dir_rewind(&lfs, &dir) => 0;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            lfs_dir_read(&lfs, &dir, &info) => 1;
            strcmp(info.name, path) => 0;
            info.size => 2;

            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_file_open(&lfs, &file, path, LFS_O_WRONLY) => 0;
            lfs_file_write(&lfs, &file, "hi", 2) => 2;
            lfs_file_close(&lfs, &file) => 0;
        }
        lfs_dir_read(&lfs, &dir, &info) => 0;

        lfs_dir_rewind(&lfs, &dir) => 0;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        lfs_dir_read(&lfs, &dir, &info) => 1;
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            lfs_dir_read(&lfs, &dir, &info) => 1;
            strcmp(info.name, path) => 0;
            info.size => 2;
        }
        lfs_dir_read(&lfs, &dir, &info) => 0;
        lfs_dir_close(&lfs, &dir) => 0;

        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            lfs_remove(&lfs, path) => 0;
        }
    }
    lfs_unmount(&lfs) => 0;
    #line 253 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_reentrant__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 1;
}

intmax_t __test__test_relocations_reentrant__CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_reentrant__FILES__0(__attribute__((unused)) void *data) {
    return 6;
}

intmax_t __test__test_relocations_reentrant__FILES__1(__attribute__((unused)) void *data) {
    return 26;
}

intmax_t __test__test_relocations_reentrant__DEPTH__2(__attribute__((unused)) void *data) {
    return 3;
}

const test_define_t __test__test_relocations_reentrant__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__FILES__1, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__DEPTH__2, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__DEPTH__2, NULL},
    },
};

bool __test__test_relocations_reentrant__filter(void) {
    return (!(DEPTH == 3 && CACHE_SIZE != 64) && 2*FILES < BLOCK_COUNT);
}

void __test__test_relocations_reentrant__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_reentrant
    #line 182 "tests/test_relocations.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        lfs_format(&lfs, cfg) => 0;
        lfs_mount(&lfs, cfg) => 0;
    }

    uint32_t prng = 1;
    const char alpha[] = "abcdefghijklmnopqrstuvwxyz";
    for (unsigned i = 0; i < CYCLES; i++) {
        // create random path
        char full_path[256];
        for (unsigned d = 0; d < DEPTH; d++) {
            sprintf(&full_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
        }

        // if it does not exist, we create it, else we destroy
        struct lfs_info info;
        int res = lfs_stat(&lfs, full_path, &info);
        if (res == LFS_ERR_NOENT) {
            // create each directory in turn, ignore if dir already exists
            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_mkdir(&lfs, path);
                assert(!err || err == LFS_ERR_EXIST);
            }

            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                lfs_stat(&lfs, path, &info) => 0;
                assert(strcmp(info.name, &path[2*d+1]) == 0);
                assert(info.type == LFS_TYPE_DIR);
            }
        } else {
            // is valid dir?
            assert(strcmp(info.name, &full_path[2*(DEPTH-1)+1]) == 0);
            assert(info.type == LFS_TYPE_DIR);

            // try to delete path in reverse order, ignore if dir is not empty
            for (unsigned d = DEPTH-1; d+1 > 0; d--) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_remove(&lfs, path);
                assert(!err || err == LFS_ERR_NOTEMPTY);
            }

            lfs_stat(&lfs, full_path, &info) => LFS_ERR_NOENT;
        }
    }
    lfs_unmount(&lfs) => 0;
    #line 359 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_reentrant_renames__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 1;
}

intmax_t __test__test_relocations_reentrant_renames__CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_reentrant_renames__FILES__0(__attribute__((unused)) void *data) {
    return 6;
}

intmax_t __test__test_relocations_reentrant_renames__FILES__1(__attribute__((unused)) void *data) {
    return 26;
}

intmax_t __test__test_relocations_reentrant_renames__DEPTH__2(__attribute__((unused)) void *data) {
    return 3;
}

const test_define_t __test__test_relocations_reentrant_renames__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__FILES__1, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__DEPTH__2, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__DEPTH__2, NULL},
    },
};

bool __test__test_relocations_reentrant_renames__filter(void) {
    return (!(DEPTH == 3 && CACHE_SIZE != 64) && 2*FILES < BLOCK_COUNT);
}

void __test__test_relocations_reentrant_renames__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_reentrant_renames
    #line 251 "tests/test_relocations.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        lfs_format(&lfs, cfg) => 0;
        lfs_mount(&lfs, cfg) => 0;
    }

    uint32_t prng = 1;
    const char alpha[] = "abcdefghijklmnopqrstuvwxyz";
    for (unsigned i = 0; i < CYCLES; i++) {
        // create random path
        char full_path[256];
        for (unsigned d = 0; d < DEPTH; d++) {
            sprintf(&full_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
        }

        // if it does not exist, we create it, else we destroy
        struct lfs_info info;
        int res = lfs_stat(&lfs, full_path, &info);
        assert(!res || res == LFS_ERR_NOENT);
        if (res == LFS_ERR_NOENT) {
            // create each directory in turn, ignore if dir already exists
            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_mkdir(&lfs, path);
                assert(!err || err == LFS_ERR_EXIST);
            }

            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                lfs_stat(&lfs, path, &info) => 0;
                assert(strcmp(info.name, &path[2*d+1]) == 0);
                assert(info.type == LFS_TYPE_DIR);
            }
        } else {
            assert(strcmp(info.name, &full_path[2*(DEPTH-1)+1]) == 0);
            assert(info.type == LFS_TYPE_DIR);

            // create new random path
            char new_path[256];
            for (unsigned d = 0; d < DEPTH; d++) {
                sprintf(&new_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
            }

            // if new path does not exist, rename, otherwise destroy
            res = lfs_stat(&lfs, new_path, &info);
            assert(!res || res == LFS_ERR_NOENT);
            if (res == LFS_ERR_NOENT) {
                // stop once some dir is renamed
                for (unsigned d = 0; d < DEPTH; d++) {
                    char path[1024];
                    strcpy(&path[2*d], &full_path[2*d]);
                    path[2*d+2] = '\0';
                    strcpy(&path[128+2*d], &new_path[2*d]);
                    path[128+2*d+2] = '\0';
                    err = lfs_rename(&lfs, path, path+128);
                    assert(!err || err == LFS_ERR_NOTEMPTY);
                    if (!err) {
                        strcpy(path, path+128);
                    }
                }

                for (unsigned d = 0; d < DEPTH; d++) {
                    char path[1024];
                    strcpy(path, new_path);
                    path[2*d+2] = '\0';
                    lfs_stat(&lfs, path, &info) => 0;
                    assert(strcmp(info.name, &path[2*d+1]) == 0);
                    assert(info.type == LFS_TYPE_DIR);
                }
                
                lfs_stat(&lfs, full_path, &info) => LFS_ERR_NOENT;
            } else {
                // try to delete path in reverse order,
                // ignore if dir is not empty
                for (unsigned d = DEPTH-1; d+1 > 0; d--) {
                    char path[1024];
                    strcpy(path, full_path);
                    path[2*d+2] = '\0';
                    err = lfs_remove(&lfs, path);
                    assert(!err || err == LFS_ERR_NOTEMPTY);
                }

                lfs_stat(&lfs, full_path, &info) => LFS_ERR_NOENT;
            }
        }
    }
    lfs_unmount(&lfs) => 0;
    #line 502 "tests/test_relocations.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_relocations__suite = {
    .name = "test_relocations",
    .path = "tests/test_relocations.toml",
    .flags = TEST_REENTRANT,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+6]){
        [BLOCK_CYCLES_i          ] = "BLOCK_CYCLES",
        [COUNT_i                 ] = "COUNT",
        [CYCLES_i                ] = "CYCLES",
        [DEPTH_i                 ] = "DEPTH",
        [FILES_i                 ] = "FILES",
        [ITERATIONS_i            ] = "ITERATIONS",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+6,
    .cases = (const struct test_case[]){
        {
            .name = "test_relocations_dangling_split_dir",
            .path = "tests/test_relocations.toml:2",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_relocations_dangling_split_dir__defines,
            .run = __test__test_relocations_dangling_split_dir__run,
        },
        {
            .name = "test_relocations_outdated_head",
            .path = "tests/test_relocations.toml:80",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_relocations_outdated_head__defines,
            .run = __test__test_relocations_outdated_head__run,
        },
        {
            .name = "test_relocations_reentrant",
            .path = "tests/test_relocations.toml:171",
            .flags = TEST_REENTRANT,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_relocations_reentrant__defines,
            .filter = __test__test_relocations_reentrant__filter,
            .run = __test__test_relocations_reentrant__run,
        },
        {
            .name = "test_relocations_reentrant_renames",
            .path = "tests/test_relocations.toml:240",
            .flags = TEST_REENTRANT,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_relocations_reentrant_renames__defines,
            .filter = __test__test_relocations_reentrant_renames__filter,
            .run = __test__test_relocations_reentrant_renames__run,
        },
    },
    .case_count = 4,
};

