// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_exhaustion.t.a.c -o tests/test_exhaustion.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_exhaustion.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_exhaustion.toml -o tests/test_exhaustion.t.a.c
//

#include "runners/test_runner.h"

#ifndef BADBLOCK_BEHAVIOR
#define BADBLOCK_BEHAVIOR_i      TEST_IMPLICIT_DEFINE_COUNT+0
#define BADBLOCK_BEHAVIOR        TEST_DEFINE(BADBLOCK_BEHAVIOR_i)
#endif
#ifndef BLOCK_CYCLES
#define BLOCK_CYCLES_i           TEST_IMPLICIT_DEFINE_COUNT+1
#define BLOCK_CYCLES             TEST_DEFINE(BLOCK_CYCLES_i)
#endif
#ifndef CYCLES
#define CYCLES_i                 TEST_IMPLICIT_DEFINE_COUNT+2
#define CYCLES                   TEST_DEFINE(CYCLES_i)
#endif
#ifndef ERASE_COUNT
#define ERASE_COUNT_i            TEST_IMPLICIT_DEFINE_COUNT+3
#define ERASE_COUNT              TEST_DEFINE(ERASE_COUNT_i)
#endif
#ifndef ERASE_CYCLES
#define ERASE_CYCLES_i           TEST_IMPLICIT_DEFINE_COUNT+4
#define ERASE_CYCLES             TEST_DEFINE(ERASE_CYCLES_i)
#endif
#ifndef FILES
#define FILES_i                  TEST_IMPLICIT_DEFINE_COUNT+5
#define FILES                    TEST_DEFINE(FILES_i)
#endif

intmax_t __test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__0(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_PROGERROR;
}

intmax_t __test__test_exhaustion_normal__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return ERASE_CYCLES / 2;
}

intmax_t __test__test_exhaustion_normal__ERASE_COUNT__0(__attribute__((unused)) void *data) {
    return 256;
}

intmax_t __test__test_exhaustion_normal__ERASE_CYCLES__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__1(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_ERASEERROR;
}

intmax_t __test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__2(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_READERROR;
}

intmax_t __test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__3(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_PROGNOOP;
}

intmax_t __test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__4(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_ERASENOOP;
}

const test_define_t __test__test_exhaustion_normal__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__0, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_normal__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_normal__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__1, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_normal__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_normal__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__2, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_normal__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_normal__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__3, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_normal__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_normal__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_normal__BADBLOCK_BEHAVIOR__4, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_normal__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_normal__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_normal__ERASE_CYCLES__0, NULL},
    },
};

void __test__test_exhaustion_normal__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_exhaustion_normal
    #line 15 "tests/test_exhaustion.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "roadrunner") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    uint32_t cycle = 0;
    while (true) {
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        for (uint32_t i = 0; i < FILES; i++) {
            // chose name, roughly random seed, and random 2^n size
            char path[1024];
            sprintf(path, "roadrunner/test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                    LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                lfs_ssize_t res = lfs_file_write(&lfs, &file, &c, 1);
                __PRETTY_ASSERT_BOOL_EQ(res == 1 || res == LFS_ERR_NOSPC, true);
                if (res == LFS_ERR_NOSPC) {
                    int err = lfs_file_close(&lfs, &file);
                    __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                    goto exhausted;
                }
            }

            int err = lfs_file_close(&lfs, &file);
            __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
            if (err == LFS_ERR_NOSPC) {
                __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                goto exhausted;
            }
        }

        for (uint32_t i = 0; i < FILES; i++) {
            // check for errors
            char path[1024];
            sprintf(path, "roadrunner/test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                char r;
                __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, &r, 1) ,  1);
                __PRETTY_ASSERT_INT_EQ(r , c);
            }

            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        cycle += 1;
    }

exhausted:
    // should still be readable
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (uint32_t i = 0; i < FILES; i++) {
        // check for errors
        char path[1024];
        sprintf(path, "roadrunner/test%d", i);
        struct lfs_info info;
        __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    LFS_WARN("completed %d cycles", cycle);
    #line 183 "tests/test_exhaustion.t.a.c"
}

intmax_t __test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__0(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_PROGERROR;
}

intmax_t __test__test_exhaustion_superblocks__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return ERASE_CYCLES / 2;
}

intmax_t __test__test_exhaustion_superblocks__ERASE_COUNT__0(__attribute__((unused)) void *data) {
    return 256;
}

intmax_t __test__test_exhaustion_superblocks__ERASE_CYCLES__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__1(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_ERASEERROR;
}

intmax_t __test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__2(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_READERROR;
}

intmax_t __test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__3(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_PROGNOOP;
}

intmax_t __test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__4(__attribute__((unused)) void *data) {
    return LFS_EMUBD_BADBLOCK_ERASENOOP;
}

const test_define_t __test__test_exhaustion_superblocks__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__0, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__1, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__2, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__3, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
    },
    {
        [BADBLOCK_BEHAVIOR_i     ] = {__test__test_exhaustion_superblocks__BADBLOCK_BEHAVIOR__4, NULL},
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_superblocks__ERASE_CYCLES__0, NULL},
    },
};

void __test__test_exhaustion_superblocks__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_exhaustion_superblocks
    #line 108 "tests/test_exhaustion.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    uint32_t cycle = 0;
    while (true) {
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        for (uint32_t i = 0; i < FILES; i++) {
            // chose name, roughly random seed, and random 2^n size
            char path[1024];
            sprintf(path, "test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                    LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                lfs_ssize_t res = lfs_file_write(&lfs, &file, &c, 1);
                __PRETTY_ASSERT_BOOL_EQ(res == 1 || res == LFS_ERR_NOSPC, true);
                if (res == LFS_ERR_NOSPC) {
                    int err = lfs_file_close(&lfs, &file);
                    __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                    goto exhausted;
                }
            }

            int err = lfs_file_close(&lfs, &file);
            __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
            if (err == LFS_ERR_NOSPC) {
                __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                goto exhausted;
            }
        }

        for (uint32_t i = 0; i < FILES; i++) {
            // check for errors
            char path[1024];
            sprintf(path, "test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                char r;
                __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, &r, 1) ,  1);
                __PRETTY_ASSERT_INT_EQ(r , c);
            }

            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        cycle += 1;
    }

exhausted:
    // should still be readable
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (uint32_t i = 0; i < FILES; i++) {
        // check for errors
        char path[1024];
        struct lfs_info info;
        sprintf(path, "test%d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    LFS_WARN("completed %d cycles", cycle);
    #line 332 "tests/test_exhaustion.t.a.c"
}

intmax_t __test__test_exhuastion_wear_leveling__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return ERASE_CYCLES / 2;
}

intmax_t __test__test_exhuastion_wear_leveling__ERASE_COUNT__0(__attribute__((unused)) void *data) {
    return 256;
}

intmax_t __test__test_exhuastion_wear_leveling__ERASE_CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_exhuastion_wear_leveling__FILES__0(__attribute__((unused)) void *data) {
    return 10;
}

const test_define_t __test__test_exhuastion_wear_leveling__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhuastion_wear_leveling__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhuastion_wear_leveling__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhuastion_wear_leveling__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhuastion_wear_leveling__FILES__0, NULL},
    },
};

void __test__test_exhuastion_wear_leveling__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_exhuastion_wear_leveling
    #line 195 "tests/test_exhaustion.toml"
    uint32_t run_cycles[2];
    const uint32_t run_block_count[2] = {BLOCK_COUNT/2, BLOCK_COUNT};

    for (int run = 0; run < 2; run++) {
        for (lfs_block_t b = 0; b < BLOCK_COUNT; b++) {
            __PRETTY_ASSERT_INT_EQ(lfs_emubd_setwear(cfg, b,
                    (b < run_block_count[run]) ? 0 : ERASE_CYCLES) ,  0);
        }

        lfs_t lfs;
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "roadrunner") ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        uint32_t cycle = 0;
        while (true) {
            __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
            for (uint32_t i = 0; i < FILES; i++) {
                // chose name, roughly random seed, and random 2^n size
                char path[1024];
                sprintf(path, "roadrunner/test%d", i);
                uint32_t prng = cycle * i;
                lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

                lfs_file_t file;
                __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                        LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

                for (lfs_size_t j = 0; j < size; j++) {
                    char c = 'a' + (TEST_PRNG(&prng) % 26);
                    lfs_ssize_t res = lfs_file_write(&lfs, &file, &c, 1);
                    __PRETTY_ASSERT_BOOL_EQ(res == 1 || res == LFS_ERR_NOSPC, true);
                    if (res == LFS_ERR_NOSPC) {
                        int err = lfs_file_close(&lfs, &file);
                        __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                        goto exhausted;
                    }
                }

                int err = lfs_file_close(&lfs, &file);
                __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                if (err == LFS_ERR_NOSPC) {
                    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                    goto exhausted;
                }
            }

            for (uint32_t i = 0; i < FILES; i++) {
                // check for errors
                char path[1024];
                sprintf(path, "roadrunner/test%d", i);
                uint32_t prng = cycle * i;
                lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

                lfs_file_t file;
                __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
                for (lfs_size_t j = 0; j < size; j++) {
                    char c = 'a' + (TEST_PRNG(&prng) % 26);
                    char r;
                    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, &r, 1) ,  1);
                    __PRETTY_ASSERT_INT_EQ(r , c);
                }

                __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
            }
            __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

            cycle += 1;
        }

exhausted:
        // should still be readable
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        for (uint32_t i = 0; i < FILES; i++) {
            // check for errors
            char path[1024];
            struct lfs_info info;
            sprintf(path, "roadrunner/test%d", i);
            __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        run_cycles[run] = cycle;
        LFS_WARN("completed %d blocks %d cycles",
                run_block_count[run], run_cycles[run]);
    }

    // check we increased the lifetime by 2x with ~10% error
    __PRETTY_ASSERT_INT_GT(run_cycles[1]*110/100 , 2*run_cycles[0]);
    #line 454 "tests/test_exhaustion.t.a.c"
}

intmax_t __test__test_exhaustion_wear_leveling_superblocks__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return ERASE_CYCLES / 2;
}

intmax_t __test__test_exhaustion_wear_leveling_superblocks__ERASE_COUNT__0(__attribute__((unused)) void *data) {
    return 256;
}

intmax_t __test__test_exhaustion_wear_leveling_superblocks__ERASE_CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_exhaustion_wear_leveling_superblocks__FILES__0(__attribute__((unused)) void *data) {
    return 10;
}

const test_define_t __test__test_exhaustion_wear_leveling_superblocks__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_leveling_superblocks__BLOCK_CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_leveling_superblocks__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_leveling_superblocks__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_leveling_superblocks__FILES__0, NULL},
    },
};

void __test__test_exhaustion_wear_leveling_superblocks__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_exhaustion_wear_leveling_superblocks
    #line 295 "tests/test_exhaustion.toml"
    uint32_t run_cycles[2];
    const uint32_t run_block_count[2] = {BLOCK_COUNT/2, BLOCK_COUNT};

    for (int run = 0; run < 2; run++) {
        for (lfs_block_t b = 0; b < BLOCK_COUNT; b++) {
            __PRETTY_ASSERT_INT_EQ(lfs_emubd_setwear(cfg, b,
                    (b < run_block_count[run]) ? 0 : ERASE_CYCLES) ,  0);
        }

        lfs_t lfs;
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

        uint32_t cycle = 0;
        while (true) {
            __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
            for (uint32_t i = 0; i < FILES; i++) {
                // chose name, roughly random seed, and random 2^n size
                char path[1024];
                sprintf(path, "test%d", i);
                uint32_t prng = cycle * i;
                lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

                lfs_file_t file;
                __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                        LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

                for (lfs_size_t j = 0; j < size; j++) {
                    char c = 'a' + (TEST_PRNG(&prng) % 26);
                    lfs_ssize_t res = lfs_file_write(&lfs, &file, &c, 1);
                    __PRETTY_ASSERT_BOOL_EQ(res == 1 || res == LFS_ERR_NOSPC, true);
                    if (res == LFS_ERR_NOSPC) {
                        int err = lfs_file_close(&lfs, &file);
                        __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                        goto exhausted;
                    }
                }

                int err = lfs_file_close(&lfs, &file);
                __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                if (err == LFS_ERR_NOSPC) {
                    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                    goto exhausted;
                }
            }

            for (uint32_t i = 0; i < FILES; i++) {
                // check for errors
                char path[1024];
                sprintf(path, "test%d", i);
                uint32_t prng = cycle * i;
                lfs_size_t size = 1 << ((TEST_PRNG(&prng) % 10)+2);

                lfs_file_t file;
                __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
                for (lfs_size_t j = 0; j < size; j++) {
                    char c = 'a' + (TEST_PRNG(&prng) % 26);
                    char r;
                    __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, &r, 1) ,  1);
                    __PRETTY_ASSERT_INT_EQ(r , c);
                }

                __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
            }
            __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

            cycle += 1;
        }

exhausted:
        // should still be readable
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        for (uint32_t i = 0; i < FILES; i++) {
            // check for errors
            char path[1024];
            struct lfs_info info;
            sprintf(path, "test%d", i);
            __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        run_cycles[run] = cycle;
        LFS_WARN("completed %d blocks %d cycles",
                run_block_count[run], run_cycles[run]);
    }

    // check we increased the lifetime by 2x with ~10% error
    __PRETTY_ASSERT_INT_GT(run_cycles[1]*110/100 , 2*run_cycles[0]);
    #line 573 "tests/test_exhaustion.t.a.c"
}

intmax_t __test__test_exhaustion_wear_distribution__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 5;
}

intmax_t __test__test_exhaustion_wear_distribution__CYCLES__0(__attribute__((unused)) void *data) {
    return 100;
}

intmax_t __test__test_exhaustion_wear_distribution__ERASE_COUNT__0(__attribute__((unused)) void *data) {
    return 256;
}

intmax_t __test__test_exhaustion_wear_distribution__ERASE_CYCLES__0(__attribute__((unused)) void *data) {
    return 4294967295;
}

intmax_t __test__test_exhaustion_wear_distribution__FILES__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_exhaustion_wear_distribution__BLOCK_CYCLES__1(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_exhaustion_wear_distribution__BLOCK_CYCLES__2(__attribute__((unused)) void *data) {
    return 3;
}

intmax_t __test__test_exhaustion_wear_distribution__BLOCK_CYCLES__3(__attribute__((unused)) void *data) {
    return 2;
}

intmax_t __test__test_exhaustion_wear_distribution__BLOCK_CYCLES__4(__attribute__((unused)) void *data) {
    return 1;
}

const test_define_t __test__test_exhaustion_wear_distribution__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_exhaustion_wear_distribution__CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_distribution__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_distribution__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__BLOCK_CYCLES__1, NULL},
        [CYCLES_i                ] = {__test__test_exhaustion_wear_distribution__CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_distribution__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_distribution__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__BLOCK_CYCLES__2, NULL},
        [CYCLES_i                ] = {__test__test_exhaustion_wear_distribution__CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_distribution__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_distribution__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__BLOCK_CYCLES__3, NULL},
        [CYCLES_i                ] = {__test__test_exhaustion_wear_distribution__CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_distribution__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_distribution__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__BLOCK_CYCLES__4, NULL},
        [CYCLES_i                ] = {__test__test_exhaustion_wear_distribution__CYCLES__0, NULL},
        [ERASE_COUNT_i           ] = {__test__test_exhaustion_wear_distribution__ERASE_COUNT__0, NULL},
        [ERASE_CYCLES_i          ] = {__test__test_exhaustion_wear_distribution__ERASE_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_exhaustion_wear_distribution__FILES__0, NULL},
    },
};

bool __test__test_exhaustion_wear_distribution__filter(void) {
    return (BLOCK_CYCLES < CYCLES/10);
}

void __test__test_exhaustion_wear_distribution__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_exhaustion_wear_distribution
    #line 394 "tests/test_exhaustion.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "roadrunner") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    uint32_t cycle = 0;
    while (cycle < CYCLES) {
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        for (uint32_t i = 0; i < FILES; i++) {
            // chose name, roughly random seed, and random 2^n size
            char path[1024];
            sprintf(path, "roadrunner/test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << 4; //((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                    LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) ,  0);

            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                lfs_ssize_t res = lfs_file_write(&lfs, &file, &c, 1);
                __PRETTY_ASSERT_BOOL_EQ(res == 1 || res == LFS_ERR_NOSPC, true);
                if (res == LFS_ERR_NOSPC) {
                    int err = lfs_file_close(&lfs, &file);
                    __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
                    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                    goto exhausted;
                }
            }

            int err = lfs_file_close(&lfs, &file);
            __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOSPC, true);
            if (err == LFS_ERR_NOSPC) {
                __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
                goto exhausted;
            }
        }

        for (uint32_t i = 0; i < FILES; i++) {
            // check for errors
            char path[1024];
            sprintf(path, "roadrunner/test%d", i);
            uint32_t prng = cycle * i;
            lfs_size_t size = 1 << 4; //((TEST_PRNG(&prng) % 10)+2);

            lfs_file_t file;
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) ,  0);
            for (lfs_size_t j = 0; j < size; j++) {
                char c = 'a' + (TEST_PRNG(&prng) % 26);
                char r;
                __PRETTY_ASSERT_INT_EQ(lfs_file_read(&lfs, &file, &r, 1) ,  1);
                __PRETTY_ASSERT_INT_EQ(r , c);
            }

            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

        cycle += 1;
    }

exhausted:
    // should still be readable
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (uint32_t i = 0; i < FILES; i++) {
        // check for errors
        char path[1024];
        struct lfs_info info;
        sprintf(path, "roadrunner/test%d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    LFS_WARN("completed %d cycles", cycle);

    // check the wear on our block device
    lfs_emubd_wear_t minwear = -1;
    lfs_emubd_wear_t totalwear = 0;
    lfs_emubd_wear_t maxwear = 0;
    // skip 0 and 1 as superblock movement is intentionally avoided
    for (lfs_block_t b = 2; b < BLOCK_COUNT; b++) {
        lfs_emubd_wear_t wear = lfs_emubd_wear(cfg, b);
        printf("%08x: wear %d\n", b, wear);
        __PRETTY_ASSERT_INT_GE(wear , 0);
        if (wear < minwear) {
            minwear = wear;
        }
        if (wear > maxwear) {
            maxwear = wear;
        }
        totalwear += wear;
    }
    lfs_emubd_wear_t avgwear = totalwear / BLOCK_COUNT;
    LFS_WARN("max wear: %d cycles", maxwear);
    LFS_WARN("avg wear: %d cycles", totalwear / (int)BLOCK_COUNT);
    LFS_WARN("min wear: %d cycles", minwear);

    // find standard deviation^2
    lfs_emubd_wear_t dev2 = 0;
    for (lfs_block_t b = 2; b < BLOCK_COUNT; b++) {
        lfs_emubd_wear_t wear = lfs_emubd_wear(cfg, b);
        __PRETTY_ASSERT_INT_GE(wear , 0);
        lfs_emubd_swear_t diff = wear - avgwear;
        dev2 += diff*diff;
    }
    dev2 /= totalwear;
    LFS_WARN("std dev^2: %d", dev2);
    __PRETTY_ASSERT_INT_LT(dev2 , 8);
    #line 767 "tests/test_exhaustion.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_exhaustion__suite = {
    .name = "test_exhaustion",
    .path = "tests/test_exhaustion.toml",
    .flags = 0,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+6]){
        [BADBLOCK_BEHAVIOR_i     ] = "BADBLOCK_BEHAVIOR",
        [BLOCK_CYCLES_i          ] = "BLOCK_CYCLES",
        [CYCLES_i                ] = "CYCLES",
        [ERASE_COUNT_i           ] = "ERASE_COUNT",
        [ERASE_CYCLES_i          ] = "ERASE_CYCLES",
        [FILES_i                 ] = "FILES",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+6,
    .cases = (const struct test_case[]){
        {
            .name = "test_exhaustion_normal",
            .path = "tests/test_exhaustion.toml:2",
            .flags = 0,
            .permutations = 5,
            .defines = (const test_define_t*)__test__test_exhaustion_normal__defines,
            .run = __test__test_exhaustion_normal__run,
        },
        {
            .name = "test_exhaustion_superblocks",
            .path = "tests/test_exhaustion.toml:95",
            .flags = 0,
            .permutations = 5,
            .defines = (const test_define_t*)__test__test_exhaustion_superblocks__defines,
            .run = __test__test_exhaustion_superblocks__run,
        },
        {
            .name = "test_exhuastion_wear_leveling",
            .path = "tests/test_exhaustion.toml:189",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_exhuastion_wear_leveling__defines,
            .run = __test__test_exhuastion_wear_leveling__run,
        },
        {
            .name = "test_exhaustion_wear_leveling_superblocks",
            .path = "tests/test_exhaustion.toml:289",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_exhaustion_wear_leveling_superblocks__defines,
            .run = __test__test_exhaustion_wear_leveling_superblocks__run,
        },
        {
            .name = "test_exhaustion_wear_distribution",
            .path = "tests/test_exhaustion.toml:386",
            .flags = 0,
            .permutations = 5,
            .defines = (const test_define_t*)__test__test_exhaustion_wear_distribution__defines,
            .filter = __test__test_exhaustion_wear_distribution__filter,
            .run = __test__test_exhaustion_wear_distribution__run,
        },
    },
    .case_count = 5,
};

