// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_relocations.t.a.c -o tests/test_relocations.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_relocations.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_relocations.toml -o tests/test_relocations.t.a.c
//

#include "runners/test_runner.h"

#ifndef BLOCK_CYCLES
#define BLOCK_CYCLES_i           TEST_IMPLICIT_DEFINE_COUNT+0
#define BLOCK_CYCLES             TEST_DEFINE(BLOCK_CYCLES_i)
#endif
#ifndef COUNT
#define COUNT_i                  TEST_IMPLICIT_DEFINE_COUNT+1
#define COUNT                    TEST_DEFINE(COUNT_i)
#endif
#ifndef CYCLES
#define CYCLES_i                 TEST_IMPLICIT_DEFINE_COUNT+2
#define CYCLES                   TEST_DEFINE(CYCLES_i)
#endif
#ifndef DEPTH
#define DEPTH_i                  TEST_IMPLICIT_DEFINE_COUNT+3
#define DEPTH                    TEST_DEFINE(DEPTH_i)
#endif
#ifndef FILES
#define FILES_i                  TEST_IMPLICIT_DEFINE_COUNT+4
#define FILES                    TEST_DEFINE(FILES_i)
#endif
#ifndef ITERATIONS
#define ITERATIONS_i             TEST_IMPLICIT_DEFINE_COUNT+5
#define ITERATIONS               TEST_DEFINE(ITERATIONS_i)
#endif

intmax_t __test__test_relocations_dangling_split_dir__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 8;
}

intmax_t __test__test_relocations_dangling_split_dir__COUNT__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_relocations_dangling_split_dir__ITERATIONS__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_dangling_split_dir__BLOCK_CYCLES__1(__attribute__((unused)) void *data) {
    return 1;
}

const test_define_t __test__test_relocations_dangling_split_dir__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_dangling_split_dir__BLOCK_CYCLES__0, NULL},
        [COUNT_i                 ] = {__test__test_relocations_dangling_split_dir__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_dangling_split_dir__ITERATIONS__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_dangling_split_dir__BLOCK_CYCLES__1, NULL},
        [COUNT_i                 ] = {__test__test_relocations_dangling_split_dir__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_dangling_split_dir__ITERATIONS__0, NULL},
    },
};

void __test__test_relocations_dangling_split_dir__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_dangling_split_dir
    #line 7 "tests/test_relocations.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    // fill up filesystem so only ~16 blocks are left
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "padding", LFS_O_CREAT | LFS_O_WRONLY) ,  0);
    uint8_t buffer[512];
    memset(buffer, 0, 512);
    while (BLOCK_COUNT - lfs_fs_size(&lfs) > 16) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, 512) ,  512);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    // make a child dir to use in bounded space
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "child") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (unsigned j = 0; j < ITERATIONS; j++) {
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_CREAT | LFS_O_WRONLY) ,  0);
            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }

        lfs_dir_t dir;
        struct lfs_info info;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "child") ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

        if (j == (unsigned)ITERATIONS-1) {
            break;
        }

        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
        }
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "child") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "test%03d_loooooooooooooooooong_name", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    for (unsigned i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 137 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_outdated_head__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 8;
}

intmax_t __test__test_relocations_outdated_head__COUNT__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_relocations_outdated_head__ITERATIONS__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_outdated_head__BLOCK_CYCLES__1(__attribute__((unused)) void *data) {
    return 1;
}

const test_define_t __test__test_relocations_outdated_head__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_outdated_head__BLOCK_CYCLES__0, NULL},
        [COUNT_i                 ] = {__test__test_relocations_outdated_head__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_outdated_head__ITERATIONS__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_outdated_head__BLOCK_CYCLES__1, NULL},
        [COUNT_i                 ] = {__test__test_relocations_outdated_head__COUNT__0, NULL},
        [ITERATIONS_i            ] = {__test__test_relocations_outdated_head__ITERATIONS__0, NULL},
    },
};

void __test__test_relocations_outdated_head__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_outdated_head
    #line 85 "tests/test_relocations.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    // fill up filesystem so only ~16 blocks are left
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "padding", LFS_O_CREAT | LFS_O_WRONLY) ,  0);
    uint8_t buffer[512];
    memset(buffer, 0, 512);
    while (BLOCK_COUNT - lfs_fs_size(&lfs) > 16) {
        __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, buffer, 512) ,  512);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    // make a child dir to use in bounded space
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "child") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (unsigned j = 0; j < ITERATIONS; j++) {
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_CREAT | LFS_O_WRONLY) ,  0);
            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }

        lfs_dir_t dir;
        struct lfs_info info;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "child") ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
            __PRETTY_ASSERT_INT_EQ(info.size ,  0);

            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_WRONLY) ,  0);
            __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hi", 2) ,  2);
            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
            __PRETTY_ASSERT_INT_EQ(info.size ,  2);

            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_WRONLY) ,  0);
            __PRETTY_ASSERT_INT_EQ(lfs_file_write(&lfs, &file, "hi", 2) ,  2);
            __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
            __PRETTY_ASSERT_INT_EQ(info.size ,  2);
        }
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

        for (unsigned i = 0; i < COUNT; i++) {
            char path[1024];
            sprintf(path, "child/test%03d_loooooooooooooooooong_name", i);
            __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
        }
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 253 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_reentrant__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 1;
}

intmax_t __test__test_relocations_reentrant__CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_reentrant__FILES__0(__attribute__((unused)) void *data) {
    return 6;
}

intmax_t __test__test_relocations_reentrant__FILES__1(__attribute__((unused)) void *data) {
    return 26;
}

intmax_t __test__test_relocations_reentrant__DEPTH__2(__attribute__((unused)) void *data) {
    return 3;
}

const test_define_t __test__test_relocations_reentrant__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__FILES__1, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant__DEPTH__2, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant__DEPTH__2, NULL},
    },
};

bool __test__test_relocations_reentrant__filter(void) {
    return (!(DEPTH == 3 && CACHE_SIZE != 64) && 2*FILES < BLOCK_COUNT);
}

void __test__test_relocations_reentrant__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_reentrant
    #line 182 "tests/test_relocations.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }

    uint32_t prng = 1;
    const char alpha[] = "abcdefghijklmnopqrstuvwxyz";
    for (unsigned i = 0; i < CYCLES; i++) {
        // create random path
        char full_path[256];
        for (unsigned d = 0; d < DEPTH; d++) {
            sprintf(&full_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
        }

        // if it does not exist, we create it, else we destroy
        struct lfs_info info;
        int res = lfs_stat(&lfs, full_path, &info);
        if (res == LFS_ERR_NOENT) {
            // create each directory in turn, ignore if dir already exists
            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_mkdir(&lfs, path);
                __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_EXIST, true);
            }

            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
                __PRETTY_ASSERT_STR_EQ(info.name, &path[2*d+1]);
                __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
            }
        } else {
            // is valid dir?
            __PRETTY_ASSERT_STR_EQ(info.name, &full_path[2*(DEPTH-1)+1]);
            __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

            // try to delete path in reverse order, ignore if dir is not empty
            for (unsigned d = DEPTH-1; d+1 > 0; d--) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_remove(&lfs, path);
                __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_NOTEMPTY, true);
            }

            __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, full_path, &info) ,  LFS_ERR_NOENT);
        }
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 359 "tests/test_relocations.t.a.c"
}

intmax_t __test__test_relocations_reentrant_renames__BLOCK_CYCLES__0(__attribute__((unused)) void *data) {
    return 1;
}

intmax_t __test__test_relocations_reentrant_renames__CYCLES__0(__attribute__((unused)) void *data) {
    return 20;
}

intmax_t __test__test_relocations_reentrant_renames__FILES__0(__attribute__((unused)) void *data) {
    return 6;
}

intmax_t __test__test_relocations_reentrant_renames__FILES__1(__attribute__((unused)) void *data) {
    return 26;
}

intmax_t __test__test_relocations_reentrant_renames__DEPTH__2(__attribute__((unused)) void *data) {
    return 3;
}

const test_define_t __test__test_relocations_reentrant_renames__defines[][TEST_IMPLICIT_DEFINE_COUNT+6] = {
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__FILES__0, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__FILES__1, NULL},
    },
    {
        [BLOCK_CYCLES_i          ] = {__test__test_relocations_reentrant_renames__BLOCK_CYCLES__0, NULL},
        [CYCLES_i                ] = {__test__test_relocations_reentrant_renames__CYCLES__0, NULL},
        [DEPTH_i                 ] = {__test__test_relocations_reentrant_renames__DEPTH__2, NULL},
        [FILES_i                 ] = {__test__test_relocations_reentrant_renames__DEPTH__2, NULL},
    },
};

bool __test__test_relocations_reentrant_renames__filter(void) {
    return (!(DEPTH == 3 && CACHE_SIZE != 64) && 2*FILES < BLOCK_COUNT);
}

void __test__test_relocations_reentrant_renames__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_relocations_reentrant_renames
    #line 251 "tests/test_relocations.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }

    uint32_t prng = 1;
    const char alpha[] = "abcdefghijklmnopqrstuvwxyz";
    for (unsigned i = 0; i < CYCLES; i++) {
        // create random path
        char full_path[256];
        for (unsigned d = 0; d < DEPTH; d++) {
            sprintf(&full_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
        }

        // if it does not exist, we create it, else we destroy
        struct lfs_info info;
        int res = lfs_stat(&lfs, full_path, &info);
        __PRETTY_ASSERT_BOOL_EQ(!res || res == LFS_ERR_NOENT, true);
        if (res == LFS_ERR_NOENT) {
            // create each directory in turn, ignore if dir already exists
            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                err = lfs_mkdir(&lfs, path);
                __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_EXIST, true);
            }

            for (unsigned d = 0; d < DEPTH; d++) {
                char path[1024];
                strcpy(path, full_path);
                path[2*d+2] = '\0';
                __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
                __PRETTY_ASSERT_STR_EQ(info.name, &path[2*d+1]);
                __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
            }
        } else {
            __PRETTY_ASSERT_STR_EQ(info.name, &full_path[2*(DEPTH-1)+1]);
            __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

            // create new random path
            char new_path[256];
            for (unsigned d = 0; d < DEPTH; d++) {
                sprintf(&new_path[2*d], "/%c", alpha[TEST_PRNG(&prng) % FILES]);
            }

            // if new path does not exist, rename, otherwise destroy
            res = lfs_stat(&lfs, new_path, &info);
            __PRETTY_ASSERT_BOOL_EQ(!res || res == LFS_ERR_NOENT, true);
            if (res == LFS_ERR_NOENT) {
                // stop once some dir is renamed
                for (unsigned d = 0; d < DEPTH; d++) {
                    char path[1024];
                    strcpy(&path[2*d], &full_path[2*d]);
                    path[2*d+2] = '\0';
                    strcpy(&path[128+2*d], &new_path[2*d]);
                    path[128+2*d+2] = '\0';
                    err = lfs_rename(&lfs, path, path+128);
                    __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_NOTEMPTY, true);
                    if (!err) {
                        strcpy(path, path+128);
                    }
                }

                for (unsigned d = 0; d < DEPTH; d++) {
                    char path[1024];
                    strcpy(path, new_path);
                    path[2*d+2] = '\0';
                    __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, path, &info) ,  0);
                    __PRETTY_ASSERT_STR_EQ(info.name, &path[2*d+1]);
                    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
                }
                
                __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, full_path, &info) ,  LFS_ERR_NOENT);
            } else {
                // try to delete path in reverse order,
                // ignore if dir is not empty
                for (unsigned d = DEPTH-1; d+1 > 0; d--) {
                    char path[1024];
                    strcpy(path, full_path);
                    path[2*d+2] = '\0';
                    err = lfs_remove(&lfs, path);
                    __PRETTY_ASSERT_BOOL_EQ(!err || err == LFS_ERR_NOTEMPTY, true);
                }

                __PRETTY_ASSERT_INT_EQ(lfs_stat(&lfs, full_path, &info) ,  LFS_ERR_NOENT);
            }
        }
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 502 "tests/test_relocations.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_relocations__suite = {
    .name = "test_relocations",
    .path = "tests/test_relocations.toml",
    .flags = TEST_REENTRANT,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+6]){
        [BLOCK_CYCLES_i          ] = "BLOCK_CYCLES",
        [COUNT_i                 ] = "COUNT",
        [CYCLES_i                ] = "CYCLES",
        [DEPTH_i                 ] = "DEPTH",
        [FILES_i                 ] = "FILES",
        [ITERATIONS_i            ] = "ITERATIONS",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+6,
    .cases = (const struct test_case[]){
        {
            .name = "test_relocations_dangling_split_dir",
            .path = "tests/test_relocations.toml:2",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_relocations_dangling_split_dir__defines,
            .run = __test__test_relocations_dangling_split_dir__run,
        },
        {
            .name = "test_relocations_outdated_head",
            .path = "tests/test_relocations.toml:80",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_relocations_outdated_head__defines,
            .run = __test__test_relocations_outdated_head__run,
        },
        {
            .name = "test_relocations_reentrant",
            .path = "tests/test_relocations.toml:171",
            .flags = TEST_REENTRANT,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_relocations_reentrant__defines,
            .filter = __test__test_relocations_reentrant__filter,
            .run = __test__test_relocations_reentrant__run,
        },
        {
            .name = "test_relocations_reentrant_renames",
            .path = "tests/test_relocations.toml:240",
            .flags = TEST_REENTRANT,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_relocations_reentrant_renames__defines,
            .filter = __test__test_relocations_reentrant_renames__filter,
            .run = __test__test_relocations_reentrant_renames__run,
        },
    },
    .case_count = 4,
};

