// Generated by ./scripts/prettyasserts.py:
//
// ./scripts/prettyasserts.py -p LFS_ASSERT tests/test_dirs.t.a.c -o tests/test_dirs.t.c
//

#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#undef _FEATURES_H

__attribute__((unused))
static void __pretty_assert_print_bool(
        const void *v, size_t size) {
    (void)size;
    printf("%s", *(const bool*)v ? "true" : "false");
}

__attribute__((unused))
static void __pretty_assert_print_int(
        const void *v, size_t size) {
    (void)size;
    printf("%"PRIiMAX, *(const intmax_t*)v);
}

__attribute__((unused))
static void __pretty_assert_print_mem(
        const void *v, size_t size) {
    const uint8_t *v_ = v;
    printf("\"");
    for (size_t i = 0; i < size && i < 16; i++) {
        if (v_[i] >= ' ' && v_[i] <= '~') {
            printf("%c", v_[i]);
        } else {
            printf("\\x%02x", v_[i]);
        }
    }
    if (size > 16) {
        printf("...");
    }
    printf("\"");
}

__attribute__((unused))
static void __pretty_assert_print_str(
        const void *v, size_t size) {
    __pretty_assert_print_mem(v, size);
}

__attribute__((unused, noinline))
static void __pretty_assert_fail(
        const char *file, int line,
        void (*type_print_cb)(const void*, size_t),
        const char *cmp,
        const void *lh, size_t lsize,
        const void *rh, size_t rsize) {
    printf("%s:%d:assert: assert failed with ", file, line);
    type_print_cb(lh, lsize);
    printf(", expected %s ", cmp);
    type_print_cb(rh, rsize);
    printf("\n");
    fflush(NULL);
    raise(SIGABRT);
}

#define __PRETTY_ASSERT_BOOL_NE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ne", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "lt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_LE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "le", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_EQ(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "eq", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GT(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "gt", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_BOOL_GE(lh, rh) do { \
    bool _lh = !!(lh); \
    bool _rh = !!(rh); \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_bool, "ge", \
                &_lh, 0, \
                &_rh, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_NE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh != _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ne", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh < _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "lt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_LE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh <= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "le", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_EQ(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh == _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "eq", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GT(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh > _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "gt", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_INT_GE(lh, rh) do { \
    __typeof__(lh) _lh = lh; \
    __typeof__(lh) _rh = rh; \
    if (!(_lh >= _rh)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_int, "ge", \
                &(intmax_t){_lh}, 0, \
                &(intmax_t){_rh}, 0); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_NE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ne", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "lt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_LE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "le", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_EQ(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "eq", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GT(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "gt", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_MEM_GE(lh, rh, size) do { \
    const void *_lh = lh; \
    const void *_rh = rh; \
    if (!(memcmp(_lh, _rh, size) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_mem, "ge", \
                _lh, size, \
                _rh, size); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_NE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) != 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ne", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) < 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "lt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_LE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) <= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "le", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_EQ(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) == 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "eq", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GT(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) > 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "gt", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)
#define __PRETTY_ASSERT_STR_GE(lh, rh) do { \
    const char *_lh = lh; \
    const char *_rh = rh; \
    if (!(strcmp(_lh, _rh) >= 0)) { \
        __pretty_assert_fail( \
                __FILE__, __LINE__, \
                __pretty_assert_print_str, "ge", \
                _lh, strlen(_lh), \
                _rh, strlen(_rh)); \
    } \
} while (0)


#line 1 "tests/test_dirs.t.a.c"
// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_dirs.toml -o tests/test_dirs.t.a.c
//

#include "runners/test_runner.h"

#ifndef COUNT
#define COUNT_i                  TEST_IMPLICIT_DEFINE_COUNT+0
#define COUNT                    TEST_DEFINE(COUNT_i)
#endif
#ifndef N
#define N_i                      TEST_IMPLICIT_DEFINE_COUNT+1
#define N                        TEST_DEFINE(N_i)
#endif

void __test__test_dirs_root__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_root
    #line 3 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 36 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_many_creation__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_many_creation__N__1(__attribute__((unused)) void *data) {
    return (6);
}

intmax_t __test__test_dirs_many_creation__N__2(__attribute__((unused)) void *data) {
    return (9);
}

intmax_t __test__test_dirs_many_creation__N__3(__attribute__((unused)) void *data) {
    return (12);
}

intmax_t __test__test_dirs_many_creation__N__4(__attribute__((unused)) void *data) {
    return (15);
}

intmax_t __test__test_dirs_many_creation__N__5(__attribute__((unused)) void *data) {
    return (18);
}

intmax_t __test__test_dirs_many_creation__N__6(__attribute__((unused)) void *data) {
    return (21);
}

intmax_t __test__test_dirs_many_creation__N__7(__attribute__((unused)) void *data) {
    return (24);
}

intmax_t __test__test_dirs_many_creation__N__8(__attribute__((unused)) void *data) {
    return (27);
}

intmax_t __test__test_dirs_many_creation__N__9(__attribute__((unused)) void *data) {
    return (30);
}

intmax_t __test__test_dirs_many_creation__N__10(__attribute__((unused)) void *data) {
    return (33);
}

intmax_t __test__test_dirs_many_creation__N__11(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_many_creation__N__12(__attribute__((unused)) void *data) {
    return (39);
}

intmax_t __test__test_dirs_many_creation__N__13(__attribute__((unused)) void *data) {
    return (42);
}

intmax_t __test__test_dirs_many_creation__N__14(__attribute__((unused)) void *data) {
    return (45);
}

intmax_t __test__test_dirs_many_creation__N__15(__attribute__((unused)) void *data) {
    return (48);
}

intmax_t __test__test_dirs_many_creation__N__16(__attribute__((unused)) void *data) {
    return (51);
}

intmax_t __test__test_dirs_many_creation__N__17(__attribute__((unused)) void *data) {
    return (54);
}

intmax_t __test__test_dirs_many_creation__N__18(__attribute__((unused)) void *data) {
    return (57);
}

intmax_t __test__test_dirs_many_creation__N__19(__attribute__((unused)) void *data) {
    return (60);
}

intmax_t __test__test_dirs_many_creation__N__20(__attribute__((unused)) void *data) {
    return (63);
}

intmax_t __test__test_dirs_many_creation__N__21(__attribute__((unused)) void *data) {
    return (66);
}

intmax_t __test__test_dirs_many_creation__N__22(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_many_creation__N__23(__attribute__((unused)) void *data) {
    return (72);
}

intmax_t __test__test_dirs_many_creation__N__24(__attribute__((unused)) void *data) {
    return (75);
}

intmax_t __test__test_dirs_many_creation__N__25(__attribute__((unused)) void *data) {
    return (78);
}

intmax_t __test__test_dirs_many_creation__N__26(__attribute__((unused)) void *data) {
    return (81);
}

intmax_t __test__test_dirs_many_creation__N__27(__attribute__((unused)) void *data) {
    return (84);
}

intmax_t __test__test_dirs_many_creation__N__28(__attribute__((unused)) void *data) {
    return (87);
}

intmax_t __test__test_dirs_many_creation__N__29(__attribute__((unused)) void *data) {
    return (90);
}

intmax_t __test__test_dirs_many_creation__N__30(__attribute__((unused)) void *data) {
    return (93);
}

intmax_t __test__test_dirs_many_creation__N__31(__attribute__((unused)) void *data) {
    return (96);
}

intmax_t __test__test_dirs_many_creation__N__32(__attribute__((unused)) void *data) {
    return (99);
}

const test_define_t __test__test_dirs_many_creation__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__8, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__9, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__10, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__11, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__12, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__13, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__14, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__15, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__16, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__17, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__18, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__19, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__20, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__21, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__22, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__23, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__24, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__25, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__26, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__27, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__28, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__29, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__30, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__31, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_creation__N__32, NULL},
    },
};

bool __test__test_dirs_many_creation__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_many_creation__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_many_creation
    #line 24 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "dir%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "dir%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 311 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_many_removal__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_many_removal__N__1(__attribute__((unused)) void *data) {
    return (14);
}

intmax_t __test__test_dirs_many_removal__N__2(__attribute__((unused)) void *data) {
    return (25);
}

intmax_t __test__test_dirs_many_removal__N__3(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_many_removal__N__4(__attribute__((unused)) void *data) {
    return (47);
}

intmax_t __test__test_dirs_many_removal__N__5(__attribute__((unused)) void *data) {
    return (58);
}

intmax_t __test__test_dirs_many_removal__N__6(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_many_removal__N__7(__attribute__((unused)) void *data) {
    return (80);
}

intmax_t __test__test_dirs_many_removal__N__8(__attribute__((unused)) void *data) {
    return (91);
}

const test_define_t __test__test_dirs_many_removal__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_removal__N__8, NULL},
    },
};

bool __test__test_dirs_many_removal__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_many_removal__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_many_removal
    #line 61 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 438 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_many_rename__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_many_rename__N__1(__attribute__((unused)) void *data) {
    return (14);
}

intmax_t __test__test_dirs_many_rename__N__2(__attribute__((unused)) void *data) {
    return (25);
}

intmax_t __test__test_dirs_many_rename__N__3(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_many_rename__N__4(__attribute__((unused)) void *data) {
    return (47);
}

intmax_t __test__test_dirs_many_rename__N__5(__attribute__((unused)) void *data) {
    return (58);
}

intmax_t __test__test_dirs_many_rename__N__6(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_many_rename__N__7(__attribute__((unused)) void *data) {
    return (80);
}

intmax_t __test__test_dirs_many_rename__N__8(__attribute__((unused)) void *data) {
    return (91);
}

const test_define_t __test__test_dirs_many_rename__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_rename__N__8, NULL},
    },
};

bool __test__test_dirs_many_rename__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_many_rename__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_many_rename
    #line 118 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "test%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "test%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char oldpath[128];
        char newpath[128];
        sprintf(oldpath, "test%03d", i);
        sprintf(newpath, "tedd%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, oldpath, newpath) ,  0);
    }
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "tedd%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);
    #line 574 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_many_reentrant__N__0(__attribute__((unused)) void *data) {
    return 5;
}

intmax_t __test__test_dirs_many_reentrant__N__1(__attribute__((unused)) void *data) {
    return 11;
}

const test_define_t __test__test_dirs_many_reentrant__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_many_reentrant__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_many_reentrant__N__1, NULL},
    },
};

bool __test__test_dirs_many_reentrant__filter(void) {
    return (BLOCK_COUNT >= 4*N);
}

void __test__test_dirs_many_reentrant__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_many_reentrant
    #line 185 "tests/test_dirs.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        err = lfs_mkdir(&lfs, path);
        __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_EXIST, true);
    }

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        err = lfs_remove(&lfs, path);
        __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOENT, true);
    }

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int i = 0; i < N; i++) {
        char oldpath[128];
        char newpath[128];
        sprintf(oldpath, "hi%03d", i);
        sprintf(newpath, "hello%03d", i);
        // YES this can overwrite an existing newpath
        __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, oldpath, newpath) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 683 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_file_creation__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_file_creation__N__1(__attribute__((unused)) void *data) {
    return (14);
}

intmax_t __test__test_dirs_file_creation__N__2(__attribute__((unused)) void *data) {
    return (25);
}

intmax_t __test__test_dirs_file_creation__N__3(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_file_creation__N__4(__attribute__((unused)) void *data) {
    return (47);
}

intmax_t __test__test_dirs_file_creation__N__5(__attribute__((unused)) void *data) {
    return (58);
}

intmax_t __test__test_dirs_file_creation__N__6(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_file_creation__N__7(__attribute__((unused)) void *data) {
    return (80);
}

intmax_t __test__test_dirs_file_creation__N__8(__attribute__((unused)) void *data) {
    return (91);
}

const test_define_t __test__test_dirs_file_creation__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_creation__N__8, NULL},
    },
};

bool __test__test_dirs_file_creation__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_file_creation__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_file_creation
    #line 273 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "file%03d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "file%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);
    #line 793 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_file_removal__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_file_removal__N__1(__attribute__((unused)) void *data) {
    return (14);
}

intmax_t __test__test_dirs_file_removal__N__2(__attribute__((unused)) void *data) {
    return (25);
}

intmax_t __test__test_dirs_file_removal__N__3(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_file_removal__N__4(__attribute__((unused)) void *data) {
    return (47);
}

intmax_t __test__test_dirs_file_removal__N__5(__attribute__((unused)) void *data) {
    return (58);
}

intmax_t __test__test_dirs_file_removal__N__6(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_file_removal__N__7(__attribute__((unused)) void *data) {
    return (80);
}

intmax_t __test__test_dirs_file_removal__N__8(__attribute__((unused)) void *data) {
    return (91);
}

const test_define_t __test__test_dirs_file_removal__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_removal__N__8, NULL},
    },
};

bool __test__test_dirs_file_removal__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_file_removal__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_file_removal
    #line 313 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "removeme%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 923 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_file_rename__N__0(__attribute__((unused)) void *data) {
    return (3);
}

intmax_t __test__test_dirs_file_rename__N__1(__attribute__((unused)) void *data) {
    return (14);
}

intmax_t __test__test_dirs_file_rename__N__2(__attribute__((unused)) void *data) {
    return (25);
}

intmax_t __test__test_dirs_file_rename__N__3(__attribute__((unused)) void *data) {
    return (36);
}

intmax_t __test__test_dirs_file_rename__N__4(__attribute__((unused)) void *data) {
    return (47);
}

intmax_t __test__test_dirs_file_rename__N__5(__attribute__((unused)) void *data) {
    return (58);
}

intmax_t __test__test_dirs_file_rename__N__6(__attribute__((unused)) void *data) {
    return (69);
}

intmax_t __test__test_dirs_file_rename__N__7(__attribute__((unused)) void *data) {
    return (80);
}

intmax_t __test__test_dirs_file_rename__N__8(__attribute__((unused)) void *data) {
    return (91);
}

const test_define_t __test__test_dirs_file_rename__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__1, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__2, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__3, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__4, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__5, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__6, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__7, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_rename__N__8, NULL},
    },
};

bool __test__test_dirs_file_rename__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_file_rename__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_file_rename
    #line 373 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "test%03d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path,
                LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "test%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < N; i++) {
        char oldpath[128];
        char newpath[128];
        sprintf(oldpath, "test%03d", i);
        sprintf(newpath, "tedd%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, oldpath, newpath) ,  0);
    }
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "tedd%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);
    #line 1062 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_file_reentrant__N__0(__attribute__((unused)) void *data) {
    return 5;
}

intmax_t __test__test_dirs_file_reentrant__N__1(__attribute__((unused)) void *data) {
    return 25;
}

const test_define_t __test__test_dirs_file_reentrant__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_file_reentrant__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_file_reentrant__N__1, NULL},
    },
};

bool __test__test_dirs_file_reentrant__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_file_reentrant__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_file_reentrant
    #line 443 "tests/test_dirs.toml"
    lfs_t lfs;
    int err = lfs_mount(&lfs, cfg);
    if (err) {
        __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    }

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        lfs_file_t file;
        __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, path, LFS_O_CREAT | LFS_O_WRONLY) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    }

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        err = lfs_remove(&lfs, path);
        __PRETTY_ASSERT_BOOL_EQ(err == 0 || err == LFS_ERR_NOENT, true);
    }

    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int i = 0; i < N; i++) {
        char oldpath[128];
        char newpath[128];
        sprintf(oldpath, "hi%03d", i);
        sprintf(newpath, "hello%03d", i);
        // YES this can overwrite an existing newpath
        __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, oldpath, newpath) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "hello%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }

    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1172 "tests/test_dirs.t.a.c"
}

void __test__test_dirs_nested__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_nested
    #line 530 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "burito",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato/baked") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato/sweet") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato/fried") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "potato") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "baked");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "fried");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "sweet");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // try removing?
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "potato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // try renaming?
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "potato", "coldpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "coldpotato", "warmpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "warmpotato", "hotpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "potato") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "coldpotato") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "warmpotato") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // try cross-directory renaming
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "coldpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "hotpotato/baked", "coldpotato/baked") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "coldpotato", "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "coldpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "hotpotato/fried", "coldpotato/fried") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "coldpotato", "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "coldpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "hotpotato/sweet", "coldpotato/sweet") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_rename(&lfs, "coldpotato", "hotpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "coldpotato") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "hotpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "baked");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "fried");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "sweet");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    
    // final remove
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato/baked") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato/fried") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  LFS_ERR_NOTEMPTY);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato/sweet") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "hotpotato") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "burito");
    __PRETTY_ASSERT_INT_EQ(info.type ,  LFS_TYPE_REG);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1302 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_recursive_remove__N__0(__attribute__((unused)) void *data) {
    return 10;
}

intmax_t __test__test_dirs_recursive_remove__N__1(__attribute__((unused)) void *data) {
    return 100;
}

const test_define_t __test__test_dirs_recursive_remove__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [N_i                     ] = {__test__test_dirs_recursive_remove__N__0, NULL},
    },
    {
        [N_i                     ] = {__test__test_dirs_recursive_remove__N__1, NULL},
    },
};

bool __test__test_dirs_recursive_remove__filter(void) {
    return (N < BLOCK_COUNT/2);
}

void __test__test_dirs_recursive_remove__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_recursive_remove
    #line 660 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "prickly-pear") ,  0);
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "prickly-pear/cactus%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "prickly-pear") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "cactus%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    lfs_unmount(&lfs);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "prickly-pear") ,  LFS_ERR_NOTEMPTY);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "prickly-pear") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    for (int i = 0; i < N; i++) {
        char path[1024];
        sprintf(path, "cactus%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        sprintf(path, "prickly-pear/%s", info.name);
        __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "prickly-pear") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "prickly-pear") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_remove(&lfs, "prickly-pear") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1387 "tests/test_dirs.t.a.c"
}

void __test__test_dirs_other_errors__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_other_errors
    #line 722 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato") ,  0);
    lfs_file_t file;
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "burito",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_file_close(&lfs, &file) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "potato") ,  LFS_ERR_EXIST);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "burito") ,  LFS_ERR_EXIST);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "burito",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  LFS_ERR_EXIST);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "potato",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  LFS_ERR_EXIST);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "tomato") ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "burito") ,  LFS_ERR_NOTDIR);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "tomato", LFS_O_RDONLY) ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "potato", LFS_O_RDONLY) ,  LFS_ERR_ISDIR);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "tomato", LFS_O_WRONLY) ,  LFS_ERR_NOENT);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "potato", LFS_O_WRONLY) ,  LFS_ERR_ISDIR);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "potato",
            LFS_O_WRONLY | LFS_O_CREAT) ,  LFS_ERR_ISDIR);

    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "/") ,  LFS_ERR_EXIST);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "/",
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_EXCL) ,  LFS_ERR_EXIST);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "/", LFS_O_RDONLY) ,  LFS_ERR_ISDIR);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "/", LFS_O_WRONLY) ,  LFS_ERR_ISDIR);
    __PRETTY_ASSERT_INT_EQ(lfs_file_open(&lfs, &file, "/",
            LFS_O_WRONLY | LFS_O_CREAT) ,  LFS_ERR_ISDIR);

    // check that errors did not corrupt directory
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
    __PRETTY_ASSERT_STR_EQ(info.name, "burito");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "potato");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // or on disk
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_REG);
    __PRETTY_ASSERT_STR_EQ(info.name, "burito");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_STR_EQ(info.name, "potato");
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1467 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_seek__COUNT__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_dirs_seek__COUNT__1(__attribute__((unused)) void *data) {
    return 128;
}

intmax_t __test__test_dirs_seek__COUNT__2(__attribute__((unused)) void *data) {
    return 132;
}

const test_define_t __test__test_dirs_seek__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [COUNT_i                 ] = {__test__test_dirs_seek__COUNT__0, NULL},
    },
    {
        [COUNT_i                 ] = {__test__test_dirs_seek__COUNT__1, NULL},
    },
    {
        [COUNT_i                 ] = {__test__test_dirs_seek__COUNT__2, NULL},
    },
};

bool __test__test_dirs_seek__filter(void) {
    return (COUNT < BLOCK_COUNT/2);
}

void __test__test_dirs_seek__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_seek
    #line 802 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, "hello") ,  0);
    for (int i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hello/kitty%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    // try seeking to each dir entry
    for (int j = 0; j < COUNT; j++) {
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        lfs_dir_t dir;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "hello") ,  0);
        struct lfs_info info;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, ".");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, "..");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        for (int i = 0; i < j; i++) {
            char path[1024];
            sprintf(path, "kitty%03d", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
            __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        }
        lfs_soff_t pos = lfs_dir_tell(&lfs, &dir);
        __PRETTY_ASSERT_INT_GE(pos , 0);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
        char path[1024];
        sprintf(path, "kitty%03d", j);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
        sprintf(path, "kitty%03u", 0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, ".");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, "..");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
        sprintf(path, "kitty%03d", j);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    }

    // try seeking to end of dir
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "hello") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

    for (int i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "kitty%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    }
    lfs_soff_t pos = lfs_dir_tell(&lfs, &dir);
    __PRETTY_ASSERT_INT_GE(pos , 0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
    char path[1024];
    sprintf(path, "kitty%03d", 0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, path);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1609 "tests/test_dirs.t.a.c"
}

intmax_t __test__test_dirs_toot_seek__COUNT__0(__attribute__((unused)) void *data) {
    return 4;
}

intmax_t __test__test_dirs_toot_seek__COUNT__1(__attribute__((unused)) void *data) {
    return 128;
}

intmax_t __test__test_dirs_toot_seek__COUNT__2(__attribute__((unused)) void *data) {
    return 132;
}

const test_define_t __test__test_dirs_toot_seek__defines[][TEST_IMPLICIT_DEFINE_COUNT+2] = {
    {
        [COUNT_i                 ] = {__test__test_dirs_toot_seek__COUNT__0, NULL},
    },
    {
        [COUNT_i                 ] = {__test__test_dirs_toot_seek__COUNT__1, NULL},
    },
    {
        [COUNT_i                 ] = {__test__test_dirs_toot_seek__COUNT__2, NULL},
    },
};

bool __test__test_dirs_toot_seek__filter(void) {
    return (COUNT < BLOCK_COUNT/2);
}

void __test__test_dirs_toot_seek__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_dirs_toot_seek
    #line 916 "tests/test_dirs.toml"
    lfs_t lfs;
    __PRETTY_ASSERT_INT_EQ(lfs_format(&lfs, cfg) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    for (int i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_mkdir(&lfs, path) ,  0);
    }
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);

    for (int j = 0; j < COUNT; j++) {
        __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
        lfs_dir_t dir;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
        struct lfs_info info;
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, ".");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, "..");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        for (int i = 0; i < j; i++) {
            char path[1024];
            sprintf(path, "hi%03d", i);
            __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
            __PRETTY_ASSERT_STR_EQ(info.name, path);
            __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        }
        lfs_soff_t pos = lfs_dir_tell(&lfs, &dir);
        __PRETTY_ASSERT_INT_GE(pos , 0);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
        char path[1024];
        sprintf(path, "hi%03d", j);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
        sprintf(path, "hi%03u", 0);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, ".");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, "..");
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
        sprintf(path, "hi%03d", j);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

        __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
        __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    }

    // try seeking to end of dir
    __PRETTY_ASSERT_INT_EQ(lfs_mount(&lfs, cfg) ,  0);
    lfs_dir_t dir;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_open(&lfs, &dir, "/") ,  0);
    struct lfs_info info;
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

    for (int i = 0; i < COUNT; i++) {
        char path[1024];
        sprintf(path, "hi%03d", i);
        __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
        __PRETTY_ASSERT_STR_EQ(info.name, path);
        __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    }
    lfs_soff_t pos = lfs_dir_tell(&lfs, &dir);
    __PRETTY_ASSERT_INT_GE(pos , 0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_rewind(&lfs, &dir) ,  0);
    char path[1024];
    sprintf(path, "hi%03d", 0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, ".");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, "..");
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  1);
    __PRETTY_ASSERT_STR_EQ(info.name, path);
    __PRETTY_ASSERT_INT_EQ(info.type , LFS_TYPE_DIR);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_seek(&lfs, &dir, pos) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_dir_read(&lfs, &dir, &info) ,  0);

    __PRETTY_ASSERT_INT_EQ(lfs_dir_close(&lfs, &dir) ,  0);
    __PRETTY_ASSERT_INT_EQ(lfs_unmount(&lfs) ,  0);
    #line 1749 "tests/test_dirs.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_dirs__suite = {
    .name = "test_dirs",
    .path = "tests/test_dirs.toml",
    .flags = TEST_REENTRANT,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+2]){
        [COUNT_i                 ] = "COUNT",
        [N_i                     ] = "N",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+2,
    .cases = (const struct test_case[]){
        {
            .name = "test_dirs_root",
            .path = "tests/test_dirs.toml:1",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_dirs_root__run,
        },
        {
            .name = "test_dirs_many_creation",
            .path = "tests/test_dirs.toml:20",
            .flags = 0,
            .permutations = 33,
            .defines = (const test_define_t*)__test__test_dirs_many_creation__defines,
            .filter = __test__test_dirs_many_creation__filter,
            .run = __test__test_dirs_many_creation__run,
        },
        {
            .name = "test_dirs_many_removal",
            .path = "tests/test_dirs.toml:57",
            .flags = 0,
            .permutations = 9,
            .defines = (const test_define_t*)__test__test_dirs_many_removal__defines,
            .filter = __test__test_dirs_many_removal__filter,
            .run = __test__test_dirs_many_removal__run,
        },
        {
            .name = "test_dirs_many_rename",
            .path = "tests/test_dirs.toml:114",
            .flags = 0,
            .permutations = 9,
            .defines = (const test_define_t*)__test__test_dirs_many_rename__defines,
            .filter = __test__test_dirs_many_rename__filter,
            .run = __test__test_dirs_many_rename__run,
        },
        {
            .name = "test_dirs_many_reentrant",
            .path = "tests/test_dirs.toml:180",
            .flags = TEST_REENTRANT,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_dirs_many_reentrant__defines,
            .filter = __test__test_dirs_many_reentrant__filter,
            .run = __test__test_dirs_many_reentrant__run,
        },
        {
            .name = "test_dirs_file_creation",
            .path = "tests/test_dirs.toml:269",
            .flags = 0,
            .permutations = 9,
            .defines = (const test_define_t*)__test__test_dirs_file_creation__defines,
            .filter = __test__test_dirs_file_creation__filter,
            .run = __test__test_dirs_file_creation__run,
        },
        {
            .name = "test_dirs_file_removal",
            .path = "tests/test_dirs.toml:309",
            .flags = 0,
            .permutations = 9,
            .defines = (const test_define_t*)__test__test_dirs_file_removal__defines,
            .filter = __test__test_dirs_file_removal__filter,
            .run = __test__test_dirs_file_removal__run,
        },
        {
            .name = "test_dirs_file_rename",
            .path = "tests/test_dirs.toml:369",
            .flags = 0,
            .permutations = 9,
            .defines = (const test_define_t*)__test__test_dirs_file_rename__defines,
            .filter = __test__test_dirs_file_rename__filter,
            .run = __test__test_dirs_file_rename__run,
        },
        {
            .name = "test_dirs_file_reentrant",
            .path = "tests/test_dirs.toml:438",
            .flags = TEST_REENTRANT,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_dirs_file_reentrant__defines,
            .filter = __test__test_dirs_file_reentrant__filter,
            .run = __test__test_dirs_file_reentrant__run,
        },
        {
            .name = "test_dirs_nested",
            .path = "tests/test_dirs.toml:528",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_dirs_nested__run,
        },
        {
            .name = "test_dirs_recursive_remove",
            .path = "tests/test_dirs.toml:656",
            .flags = 0,
            .permutations = 2,
            .defines = (const test_define_t*)__test__test_dirs_recursive_remove__defines,
            .filter = __test__test_dirs_recursive_remove__filter,
            .run = __test__test_dirs_recursive_remove__run,
        },
        {
            .name = "test_dirs_other_errors",
            .path = "tests/test_dirs.toml:720",
            .flags = 0,
            .permutations = 1,
            .run = __test__test_dirs_other_errors__run,
        },
        {
            .name = "test_dirs_seek",
            .path = "tests/test_dirs.toml:798",
            .flags = 0,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_dirs_seek__defines,
            .filter = __test__test_dirs_seek__filter,
            .run = __test__test_dirs_seek__run,
        },
        {
            .name = "test_dirs_toot_seek",
            .path = "tests/test_dirs.toml:912",
            .flags = 0,
            .permutations = 3,
            .defines = (const test_define_t*)__test__test_dirs_toot_seek__defines,
            .filter = __test__test_dirs_toot_seek__filter,
            .run = __test__test_dirs_toot_seek__run,
        },
    },
    .case_count = 14,
};

