// Generated by ./scripts/test.py:
//
// ./scripts/test.py -c tests/test_entries.toml -o tests/test_entries.t.a.c
//

#include "runners/test_runner.h"

#ifndef CACHE_SIZE
#define CACHE_SIZE_i             TEST_IMPLICIT_DEFINE_COUNT+0
#define CACHE_SIZE               TEST_DEFINE(CACHE_SIZE_i)
#endif

intmax_t __test__test_entries_grow__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_grow__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_grow__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_grow__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_grow__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_grow
    #line 10 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 20
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 20;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 20
    sprintf(path, "hi2"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 20
    sprintf(path, "hi3"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi0 20
    sprintf(path, "hi0"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 20
    sprintf(path, "hi2"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 20
    sprintf(path, "hi3"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_unmount(&lfs) => 0;
    #line 120 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_shrink__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_shrink__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_shrink__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_shrink__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_shrink__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_shrink
    #line 103 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 20
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 20;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 20
    sprintf(path, "hi2"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 20
    sprintf(path, "hi3"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi0 20
    sprintf(path, "hi0"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 20
    sprintf(path, "hi2"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 20
    sprintf(path, "hi3"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_unmount(&lfs) => 0;
    #line 229 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_spill__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_spill__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_spill__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_spill__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_spill__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_spill
    #line 196 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 200
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 200;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_unmount(&lfs) => 0;
    #line 322 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_push_spill__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_push_spill__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_push_spill__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_push_spill__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_push_spill__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_push_spill
    #line 273 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 200
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 200;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_unmount(&lfs) => 0;
    #line 431 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_push_spill_two__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_push_spill_two__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_push_spill_two__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_push_spill_two__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_push_spill_two__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_push_spill_two
    #line 366 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 200
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 200;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi4 200
    sprintf(path, "hi4"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi1 20
    sprintf(path, "hi1"); size = 20;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi4 200
    sprintf(path, "hi4"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_unmount(&lfs) => 0;
    #line 555 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_drop__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_drop__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_drop__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_drop__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_drop__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_drop
    #line 474 "tests/test_entries.toml"
    uint8_t wbuffer[1024];
    uint8_t rbuffer[1024];

    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;
    lfs_mount(&lfs, cfg) => 0;

    // write hi0 200
    char path[1024];
    lfs_size_t size;
    sprintf(path, "hi0"); size = 200;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi1 200
    sprintf(path, "hi1"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;
    // write hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_close(&lfs, &file) => 0;

    lfs_remove(&lfs, "hi1") => 0;
    struct lfs_info info;
    lfs_stat(&lfs, "hi1", &info) => LFS_ERR_NOENT;
    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi2 200
    sprintf(path, "hi2"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_remove(&lfs, "hi2") => 0;
    lfs_stat(&lfs, "hi2", &info) => LFS_ERR_NOENT;
    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    // read hi3 200
    sprintf(path, "hi3"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_remove(&lfs, "hi3") => 0;
    lfs_stat(&lfs, "hi3", &info) => LFS_ERR_NOENT;
    // read hi0 200
    sprintf(path, "hi0"); size = 200;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_size(&lfs, &file) => size;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    lfs_remove(&lfs, "hi0") => 0;
    lfs_stat(&lfs, "hi0", &info) => LFS_ERR_NOENT;

    lfs_unmount(&lfs) => 0;
    #line 674 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_create_too_big__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_create_too_big__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_create_too_big__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_create_too_big__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_create_too_big__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_create_too_big
    #line 577 "tests/test_entries.toml"
    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;

    lfs_mount(&lfs, cfg) => 0;
    char path[1024];
    memset(path, 'm', 200);
    path[200] = '\0';

    lfs_size_t size = 400;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    uint8_t wbuffer[1024];
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_close(&lfs, &file) => 0;

    size = 400;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    uint8_t rbuffer[1024];
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    lfs_unmount(&lfs) => 0;
    #line 718 "tests/test_entries.t.a.c"
}

intmax_t __test__test_entries_resize_too_big__CACHE_SIZE__0(__attribute__((unused)) void *data) {
    return 512;
}

const test_define_t __test__test_entries_resize_too_big__defines[][TEST_IMPLICIT_DEFINE_COUNT+1] = {
    {
        [CACHE_SIZE_i            ] = {__test__test_entries_resize_too_big__CACHE_SIZE__0, NULL},
    },
};

bool __test__test_entries_resize_too_big__filter(void) {
    return (CACHE_SIZE % PROG_SIZE == 0 && CACHE_SIZE == 512);
}

void __test__test_entries_resize_too_big__run(__attribute__((unused)) struct lfs_config *cfg) {
    // test case test_entries_resize_too_big
    #line 605 "tests/test_entries.toml"
    lfs_t lfs;
    lfs_format(&lfs, cfg) => 0;

    lfs_mount(&lfs, cfg) => 0;
    char path[1024];
    memset(path, 'm', 200);
    path[200] = '\0';

    lfs_size_t size = 40;
    lfs_file_t file;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    uint8_t wbuffer[1024];
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_close(&lfs, &file) => 0;

    size = 40;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    uint8_t rbuffer[1024];
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;

    size = 400;
    lfs_file_open(&lfs, &file, path,
            LFS_O_WRONLY | LFS_O_CREAT | LFS_O_TRUNC) => 0;
    memset(wbuffer, 'c', size);
    lfs_file_write(&lfs, &file, wbuffer, size) => size;
    lfs_file_close(&lfs, &file) => 0;

    size = 400;
    lfs_file_open(&lfs, &file, path, LFS_O_RDONLY) => 0;
    lfs_file_read(&lfs, &file, rbuffer, size) => size;
    memcmp(rbuffer, wbuffer, size) => 0;
    lfs_file_close(&lfs, &file) => 0;
    lfs_unmount(&lfs) => 0;
    #line 775 "tests/test_entries.t.a.c"
}

__attribute__((section("_test_suites"), aligned(1)))
const struct test_suite __test__test_entries__suite = {
    .name = "test_entries",
    .path = "tests/test_entries.toml",
    .flags = 0,
    .define_names = (const char *const[TEST_IMPLICIT_DEFINE_COUNT+1]){
        [CACHE_SIZE_i            ] = "CACHE_SIZE",
    },
    .define_count = TEST_IMPLICIT_DEFINE_COUNT+1,
    .cases = (const struct test_case[]){
        {
            .name = "test_entries_grow",
            .path = "tests/test_entries.toml:8",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_grow__defines,
            .filter = __test__test_entries_grow__filter,
            .run = __test__test_entries_grow__run,
        },
        {
            .name = "test_entries_shrink",
            .path = "tests/test_entries.toml:101",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_shrink__defines,
            .filter = __test__test_entries_shrink__filter,
            .run = __test__test_entries_shrink__run,
        },
        {
            .name = "test_entries_spill",
            .path = "tests/test_entries.toml:194",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_spill__defines,
            .filter = __test__test_entries_spill__filter,
            .run = __test__test_entries_spill__run,
        },
        {
            .name = "test_entries_push_spill",
            .path = "tests/test_entries.toml:271",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_push_spill__defines,
            .filter = __test__test_entries_push_spill__filter,
            .run = __test__test_entries_push_spill__run,
        },
        {
            .name = "test_entries_push_spill_two",
            .path = "tests/test_entries.toml:364",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_push_spill_two__defines,
            .filter = __test__test_entries_push_spill_two__filter,
            .run = __test__test_entries_push_spill_two__run,
        },
        {
            .name = "test_entries_drop",
            .path = "tests/test_entries.toml:472",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_drop__defines,
            .filter = __test__test_entries_drop__filter,
            .run = __test__test_entries_drop__run,
        },
        {
            .name = "test_entries_create_too_big",
            .path = "tests/test_entries.toml:575",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_create_too_big__defines,
            .filter = __test__test_entries_create_too_big__filter,
            .run = __test__test_entries_create_too_big__run,
        },
        {
            .name = "test_entries_resize_too_big",
            .path = "tests/test_entries.toml:603",
            .flags = 0,
            .permutations = 1,
            .defines = (const test_define_t*)__test__test_entries_resize_too_big__defines,
            .filter = __test__test_entries_resize_too_big__filter,
            .run = __test__test_entries_resize_too_big__run,
        },
    },
    .case_count = 8,
};

